### ISSUE TITLE
Specify: Customized verbatim text fields

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#122]
Pip: Verbatim fields needed in Specify to capture taxon, geography and label OCR text which also records the source of the verbatim data.

**Comment by FedorSteeman** [comment]
@PipBrewer  Is this the same as #220 ?

**Comment by PipBrewer** [comment]
Yep

**Comment by FedorSteeman** [comment]
@jlegind Another one to be merged then

**Comment by jlegind** [comment]
#220 to be merged with which one? #122?

**Comment by FedorSteeman** [comment]
Well if you compare the two, you'll see that #220 has a lot more information and specifications. So close #122 as duplicate.

**Comment by jlegind** [comment]
Duplicate
