### ISSUE TITLE
NHMA: Barcodes encode subcollection

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#123]
For NHMA, barcodes will need to encode subcollection as well as base number and that will need to be parsed out in app once scanned

**Comment by PipBrewer** [comment]
@chelseagraham To let us know what the form of the encoded information will be within the data matrix when she hears back from them

**Comment by PipBrewer** [comment]
Chelsea Graham has fed back from a conversation with Simon at NHMA that they do not need the collection encoded into the barcode - they are happy with just 9 digits. Just waiting on confirmation from Chelsea on this.

**Comment by jlegind** [comment]
Chelsea has confirmed and NHMA is satisfied with nine digit barcodes.
