### ISSUE TITLE
Database files too big for Github

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#185]
## Issue
Github limitations.

Github has a limit for blob files, like the sqlite database and that is 100 MB which we're currently hitting. 
We need a different way to keep the base database file in the repository. 
The taxonname table is already very large and will grow over time. The storage table also has the potential be grow.

### What is the expected acceptable result.
A method for incorporating the split database files into the app SQLite DB.
The best way is to empty the database file, so it has only structure and no content (called "fresh"). 
The predefined data, including especially taxon and storage spines, will be stored in SQL files that can be run to populate a fresh database. 

Another advantage of this is version control of the predefined data. 

### Challenges and risks
It is a much more involved process for the team because it requires running a batch script with several SQL scripts involved.
There is also the issue of maintaining and updating these SQL files as changes occur. We had to do an update on the storage SQL due to a change in the collection name made by the collections manager.

- [x] Extract SQL scripts for predefined data
- [x] Code or process for populating a fresh database 
-~[ ] Integrate with compilation of installer program~
- [x] Document process 

Alternatively, the database could be populated from the Specify7 API upon reinstallation.

**Comment by jlegind** [comment]
The predefined data SQL files can be found here: 
https://github.com/NHMDenmark/Mass-Digitizer/tree/main/MassDigitizer/sql/editions 

There are SQL files specific to NHMD and to NHMA.
