### ISSUE TITLE
Display adjacent records 

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#204]
## Issue
We want digitizers to have an overview of what they just did and that can be solved with a post-view pane showing the last three records prior to the one being worked on.

It's difficult to know that your entries or changes are saved. It would be helpful to have a display of the records that you have just worked on for reference. Perhaps this pane could display the last records entered and highlight which record you are currently on, which would be specifically handy when editing.

If it is easy to implement this could be a Priority 1. However, if very time consuming this may need to be part of version 2 release and should be Priority 2.

**Comment by jlegind** [comment]
In early 2023 it was decided that the adjacent records table should be a display with no functionality.
