### ISSUE TITLE
Change multispecimen sheet to multispecimen object in Ui

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#218]
## Issue
A more generic term was needed for the multispecimen concept. 

This is so it is relevant for pinned insects as well until we are at the point we can customise the UI for different collections

**Comment by jlegind** [comment]
Two concepts were implemented:
Multi Specimen Object (example: Multiple specimens on one herbarium sheet)
Multi Object Specimen (this could be a specimen covering multiple sheets)

This issue is covered by #340
