### ISSUE TITLE
Collection object notes table

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#220]
Investigate table linked to collection object in Specify for holding tabular notes format... 

It looks like we can repurpose the collectionobjectproperty table in Specify, which has many customizable fields including a "Remarks" field. It also holds date, and number fields, as well as a number of generic text fields. 

It's not used by any collections except NHMD Exhibitions, which doesn't parttake.

**Comment by PipBrewer** [comment]
Make it so!

**Comment by FedorSteeman** [comment]
Implemented for Vascular Plants in production: 
![image](https://user-images.githubusercontent.com/10909008/222687108-54d0bd9f-ea2b-4bec-9f0f-54f8a7478e55.png)

**Comment by FedorSteeman** [comment]
Implemented for Entomology in production: 
![image](https://user-images.githubusercontent.com/10909008/222693627-b7cf2a36-3d72-45f0-af5e-30f5de36b3e4.png)

**Comment by FedorSteeman** [comment]
To be reopened if needed for other collections.

**Comment by jlegind** [comment]
Merging #122
