### ISSUE TITLE
Navigating records behaviour

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#259]
The app currently behaves in a confusing way when navigating through records. Not sure how much can be easily resolved without investment of time, so probably need to discuss this.

The 3 record list that shows at the bottom of the screen: It is not possible to scroll through these using the arrows at the right of this box

Clicking on the records in this list, changes the position of what you can see in the list and combined with the inability to scroll through them, becomes confusing.

**3**. This behaviour combined with the fact that when we edit a previous record and press save, it retains that information from that saved record and then becomes the next record to be digitised (removes the barcode), is confusing and a bit worrying. A check has to be implemented: Is the save action on a novel record or on a previous one!

I would suggest, preventing clicking on or interacting with the 3 record list you can see at the bottom - remove the scroll bar, remove the ability to click on the record. Only navigate using the forward and back buttons.

**I would also strongly suggest removing the behaviour that pressing save after editing a previous record, then removes the barcode and you can then start digitising again. I would suggest, needing to move forwards again using the buttons.**

Finally, I think we should implement a first record button and a last record button to ease navigation.

In essence this ticket should be about discussing the above options and then we decide what we can implement and when in related tickets. Suggestion to discuss this today at usual meeting.

------------------------------
EDIT defining tasks: 

- [x] 1. Remove scroll bar 
- [x] 2. Remove ability to click on records
- [x] 3. Remain on record after saving edits to existing record 
~~- [ ] 4. First & Last record button~~ might get reimplemented later.
- [x] 5. Shows records from other collections

**Comment by FedorSteeman** [comment]
All resolved in release v0.3.2
