### ISSUE TITLE
Can't see object remarks table in Vascular Plants or Entomology (or anywhere)

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#269]
NHMDenmark/Mass-Digitizer#220

**Comment by jlegind** [comment]
Surely this is "object remarks **field**"

**Comment by FedorSteeman** [comment]
I have some recollection the discussion of adding notes to the remarks field in a tabular fashion.

**Comment by FedorSteeman** [comment]
Ah, it's all described in #220 

It's here: 

![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/a57d4840-e020-4a12-a171-bc4c6e747f6b)
