### ISSUE TITLE
Additional checkbox for specimen that needs repair

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#271]
Christian Lange requested a check box for specimens which need repair or the attention of a collection manager. This was discussed on 22/02/2023 with Olof and others. Whilst this is unlikely to actually prompt any action from the collection manager (nobody has the time), it would be a good way to collect data on the collection on the scale of issues.

**User/project Requirements**

- A check box to be added to the UI in a place which works with the flow of entering data (for all collections)
- Check box should be named something appropriate and broad enough to convey meaning
- Checkbox should align with field in Specify so data is incorporated into specimen records
- It should be possible to easily search Specify records to find all those that had check box checked whilst digitising to facilitate condition audits
- Checking the check box should not persist (be "sticky") to the next record after saving.

**Comment by jlegind** [comment]
First speak to Matilde about where the checkbox should be placed and what the label should read. In the digitization workflow there is a moment where the 'need of repair' becomes apparent. The position of the checkbox should line up with that moment. 
There is a need to understand where in Specify such data would fit - poke around Specify interface first before leaning on Fedor.
Next have a talk with Christian Lange about positioning the checkbox.

**Comment by jlegind** [comment]
Matilde was not available for meeting due to the pinned insects rush, but I managed to secure a zoom meeting with Jens Soelberg.

**Comment by jlegind** [comment]
I had a zoom call with Jens Soederberg and he had no strong opinions on where to have the 'Damaged specimen" tick box, yet we agreed that having it between 'type status' and 'notes' would make sense.
My investigation into this is based on : At which point in the workflow does it become apparent for the digitizer that the specimen is damaged and needs attention? This should dictate where the tick box is placed.

**Comment by jlegind** [comment]
@FedorSteeman , I need to know about how the 'damaged specimen' value fits into Specify.  
The app 'specimen' table will be expanded with this property - and I need to come up with a value to be submitted.
"Damaged specimen" should be sufficient.

**Comment by jlegind** [comment]
Chelsea agrees that sticking the 'needs repair' checkbox between "Notes" and "container ID" would fit with the digitization workflow.

**Comment by jlegind** [comment]
Done and tested.

**Comment by PipBrewer** [comment]
After speaking to Fedor, we agreed that using an existing field in Specify meant to record object condition would be useful (and one is present, but not currently activated). The check box in the digitisation app could translate into a standard phrase during import to Specify - e.g., "Needs attention" or something similar. This exact phrase could be searched in Specify to identify the specimen records with this. However, we need to ensure collection managers are happy with this. @FedorSteeman will implement this in Specify Test and we will send a screen shot to collection managers (particularly Christian and Jens) for their opinion.

**Comment by jlegind** [comment]
Contacted Christian Lange about the solution for the 'Specimen needs repair' checkbox and awaiting his reply.
If go ahead is given, the implementation is ready and the update shouldn't take long.

**Comment by jlegind** [comment]
Christian Lange gave an OK to the proposed checkbox setup (email 06-09-2023)

**Comment by jlegind** [comment]
Remember to ask Chelsea to update the training material.
