### ISSUE TITLE
Update user documentation

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#275]
After feedback from Christian Lange, I think we need to add some more instructions in the attached document (page 5).

At the moment, we have this:

_Clicking on the link in the slack channel will take you to the Github page: https://github.com/NHMDenmark/Mass-Digitizer/releases 
Here you will see be all of the releases of the app.

Select the newest release and it will now download onto your computer. Once it has been downloaded, you can install it._ 

But I think we need to add screen shots of the list of releases, then clicking on the top one and then arrow to the .exe file to click on. We then need to show what happens in your browser and where to click to start installation (show examples using Firefox and Chrome). Mention that Explorer might not work. Also show where downloads go in downloads folder in case it is easier to look there.

Incidentally when doing screen shots, please embed arrows in the image. Please also try and be consistent with colour and weighting of arrow so there is a sense of consistency through the document. 

And perhaps also mention somewhere that currently we are only supporting windows, but hope to include mac users in future iterations – perhaps put that in trouble shooting.

Finally - we should add into the troubleshooting section, information on how to get log files if there is an issue?

[Mass Digitisation App workflow and user guide v1_final.docx](https://github.com/NHMDenmark/Mass-Digitizer/files/10821743/Mass.Digitisation.App.workflow.and.user.guide.v1_final.docx)

**Comment by jlegind** [comment]
User Guide updated wit detailed instructions and screenshots in the guide.
