### ISSUE TITLE
Possible browser issue

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#276]
Try viewing latest versions of App in Github in different browsers on different computers and seeing if can see the .exe file, or if it has trouble (or delays) in being visible.

**Comment by jlegind** [comment]
Chrome and Firefox are the recommended browsers for downloading in the User Guide.

**Comment by FedorSteeman** [comment]
I would not recommend using an outdated browser like Internet Explorer. I have no idea why KU-IT still distribute on our computers, but perhaps we just add a note in the guide/documentation.

**Comment by jlegind** [comment]
In the user guide there is a notification about the problems with MS Explorer and a warning. It is mentioned that Chrome and Firefox are good fits for the download step.
