### ISSUE TITLE
Not writing sticky fields after navigation

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#283]

**Comment by PipBrewer** [comment]
After navigating back through records and then to latest records - adding a new records retains the info in the sticky fields in the form view, but if you look at the DB and list view - they haven't written to the DB. Log file attached.

[log-20230303120345.log](https://github.com/NHMDenmark/Mass-Digitizer/files/10881257/log-20230303120345.log)

**Comment by FedorSteeman** [comment]
I need a more detailed sequence of events for I cannot replicate: 
![image](https://user-images.githubusercontent.com/10909008/222729606-d1388dba-7e0e-4b26-abf5-eb457645c5be.png)

**Comment by jlegind** [comment]
Jan's actions on oneDrive laptop:
1. Started the application.
2. Logged in as 'test' and chose NHMD Entomology.
3. Went back one record (takes me to the latest entry as expected)
4. Went forward one step which clears the record ID
5. Inputted catalog number and saved. == Record sticky fields persisted!!
![app_032_sticky](https://user-images.githubusercontent.com/5330066/222733049-b74684dd-04cb-4f2f-849e-9b1f1fdf20dd.png)

Will try with two  and three steps back.

**Comment by FedorSteeman** [comment]
Issue confirmed fixed without side-effects
