### ISSUE TITLE
Full agent name doesn't appear in table as per issue #217

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#286]
Jan to check in all collectoins and institutions in the app

**Comment by FedorSteeman** [comment]
Test for Aarhus ENT

**Comment by jlegind** [comment]
I found a difference in the way NHMA stores 'agentfullname'. 
I can only log in as user 'test' and not my own user 'jan.legind'. Now instead of saving the fullname as "Test T. Test" as NHMD does, I am saved as "Test Test. Test". It is a very slight difference but it is there.

**Comment by jlegind** [comment]
It was agreed that the full name of the agent was not needed since Specify requires the atomic names.

**Comment by jlegind** [comment]
As decided in #217
