### ISSUE TITLE
Record storage rank & map via export

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#289]
Storage locations in specimen table in app database are of mixed rank which makes importing to Specify difficult

- [x] Fix SQL recreate predefined data inserts to include rankname 
- [x] Change specimen table to accomdate storagerankname 
- [x] Change date entry to save values to column storagerankname

**Comment by FedorSteeman** [comment]
Using the Storage.sql script for each collection under editions, we need to adjust the storage table in the local app database as follows: 
1. Add rankname column 
1. Add lines for parent levels: institution, site/building, collection (and other levels if need be)

**Comment by jlegind** [comment]
With the storagetreedefitem table copied to SQLite I was able to make this SQL statement pulling the storage rank into the storage table: 

`SELECT t1.id, t1.spid, t1.name, t1.fullname, t1.parentfullname, t1.collectionid, t1.treedefid, sr.title as storagerank FROM 
(SELECT *, substr(name, 1, pos-1) as storagetitle FROM 
(SELECT *, instr(name, ' ') as pos FROM storage ))t1
LEFT JOIN storage_rank sr ON t1.storagetitle = sr.Title;`

SQLite does not have a built in string split function so that is why the quirky subquery is needed.

I am now considering creating a script that produces a file similar to the editions/NHMD/tracheophyta/Storage.sql file, but with the storage_rank column added.

**Comment by jlegind** [comment]
Solution proposed:  

SELECT CONCAT_WS(' | ', '(' s1.institution, s1.building, s1.collection, s1.unit, '(SELECT id FROM collection WHERE spid = 688130 AND institutionid = 1)),') FROM
  (SELECT 'Natural History Museum of Denmark' AS institution, t1.Name AS building, [t2.name](http://t2.name/) AS collection,
    CASE WHEN t2.Name = 'Herbarium C: Danish Vascular Plant Collection' then CONCAT('Box ', t3.Name)  
    ELSE CONCAT('Shelf ', t3.Name)
    END AS unit
  FROM storage AS t1
LEFT JOIN storage AS t2 ON t2.ParentID = t1.storageID
LEFT JOIN storage AS t3 ON t3.parentID = 
  t2.storageID
WHERE t1.Name IN ( 'Priorparken') AND t2.Name LIKE ('Herbarium%'))s1;

**Comment by FedorSteeman** [comment]
I don't understand this solution...

**Comment by FedorSteeman** [comment]
Reopening since the rankname column still needs to be added to the app db and Storage.sql files. 

Also the storagerankname should be recorded into the specimen table during digitization.

**Comment by jlegind** [comment]
Minor update - start and end parantheses in top SELECT statement.

```
SELECT CONCAT_WS(' | ', '(', t1.stor, t1.unit, '(SELECT id FROM collection WHERE spid = 688130 AND institutionid = 1)),') AS storage_  FROM
(
SELECT CONCAT_WS(' | ', 'Natural History Museum of Denmark' , t1.Name , t2.name) AS stor,
case when t2.Name = 'Herbarium C: Danish Vascular Plant Collection' then CONCAT('Box ', t3.Name)
ELSE CONCAT('Shelf ', t3.Name)
END AS unit
FROM storage AS t1  
LEFT JOIN storage AS t2 ON t2.ParentID = t1.storageID
LEFT JOIN storage AS t3 ON t3.parentID = t2.storageID
WHERE t1.Name IN ( 'Priorparken') AND t2.Name LIKE ('Herbarium%')
)t1;
```

**Comment by jlegind** [comment]
Final update, now with rank at index 4 in the concatenated column:

SELECT CONCAT_WS(' | ', '(', t1.stor, t1.unit, t1.rank_name, '(SELECT id FROM collection WHERE spid = 688130 AND institutionid = 1)),') AS storage_  FROM
(
SELECT CONCAT_WS(' | ', 'Natural History Museum of Denmark' , t1.Name , t2.name ) AS stor, stdi.name AS rank_name,
case when t2.Name = 'Herbarium C: Danish Vascular Plant Collection' then CONCAT('Box ', t3.Name)
ELSE CONCAT('Shelf ', t3.Name)
END AS unit, stdi.Name AS rankname, t3.name AS index_
FROM storage AS t1
LEFT JOIN storage AS t2 ON t2.ParentID = t1.storageID
LEFT JOIN storage AS t3 ON t3.parentID = t2.storageID
LEFT JOIN storagetreedefitem stdi ON t3.RankID = stdi.RankID
WHERE t1.Name IN ( 'Priorparken') AND t2.Name LIKE ('Herbarium%')
)t1;

**Comment by jlegind** [comment]
Currently March 2023, the policy is to run the SQL above and pasting it into a SQL file. 

- Replace the existing Storage.sql file in ...Documents\dassco\MassDigitizer\sql\editions\NHMD\tracheophyta\Storage.sql.
- Run the prepare-db.bat bash file as described here https://github.com/NHMDenmark/Mass-Digitizer/blob/main/README.md .
