### ISSUE TITLE
De-concatenate agents in specimen table in db

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#290]

**Comment by jlegind** [comment]
Agent name must be split into first-name, middle-name/initial, last-name in db.sqlite3 'specimen' table.

**Comment by jlegind** [comment]
Splitting name on the '.' period character.
pip.brewer becomes firstname:pip, lastname:brewer

**Comment by FedorSteeman** [comment]
You cannot derive the agent name from the username ...

**Comment by FedorSteeman** [comment]
What needs to happen is that that the agent name elements are not concatenated when fetched from the Specify7 API, but kept separately.
