### ISSUE TITLE
Conversion of specimen table to workbench import file

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#293]
## Issue
The specimen table is in itself not fully fit for import into Specify. Some kind of conversion needs to happen in order to make this happen. 

We either: 
* Change the specimen table itself so it can be directly imported as-is 
* Add a conversion feature for creating export files ready for import 

### Acceptable solution
In either case analogies of the following columns need to be rendered: 
- [x] Perhaps recaption "multispecimen" as "containername" 
- [x] taxon name columns as "family", "genus", "species" and infraspecific taxa 
- [x] storage name columns as "institution" "site" "collection" and lower ranks like "box" and "shelf"
- [x] Column "locality name" for linking "georegionname" to locality (will just mirror georegionname value)
- [x] Column "agentfullname" as "cataloger first name" "cataloger middle" & "cataloger last name" (Covered by #290 )
- [x] Add "publish" column to be mapped to "collectionobject.yesno1" 
- [x] Add flag that is mapped into field in taxon record when new taxon has been entered (indicated by empty taxonspid)
- [x] Handle new taxa by parsing taxonfullname because taxonrankname is not set (assume subgeneric taxa)

**Comment by PipBrewer** [comment]
Needs testing in workbench
