### ISSUE TITLE
App freezes when attempting Shift-Tab from "Save" button

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#299]
App freezes when attempting Shift-Tab from "Save" button

Attached log indicates that the app goes in an infinite loop cykling between "inpTaxonName" and "inpCatalogNumber"

[log-20230504133752.log](https://github.com/NHMDenmark/Mass-Digitizer/files/11397435/log-20230504133752.log)

**Comment by jlegind** [comment]
That behavior has been fixed.
