### ISSUE TITLE
Remove taxon name requirement popup

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#300]
A new popup appears whenever the taxon name is left empty when leaving that field. 

![image](https://user-images.githubusercontent.com/10909008/236205714-30d0ccd9-bdac-429c-9bbb-2900cf214928.png)

It has never been a requirement that the taxon name cannot be left empty, so this should be removed.

**Comment by jlegind** [comment]
Pop-up removed.
