### ISSUE TITLE
Focus no longer on barcode field after new record saved

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#301]
When saving a new record, the focus now longer goes back to the (reset) barcode field. 

This is a requirement for fast digitization. The user should not have to click back to the barcode field on every save, but the focus should stay there, so the user has the option of quickly scanning or entering the next barcode.

**Comment by jlegind** [comment]
The save action sends focus back to the barcode field now.

**Comment by jlegind** [comment]
Fixed by field focus 'inpCatalogNumber' in Save.
