### ISSUE TITLE
Taxon rank name for new taxa is not recorded or parsed

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#305]
Two intertwined issues: 

- [x] During app execution, the taxon rank name is not recorded 
- [x] During OpenRefine script post-processing, the names are still parsed correctly, but the corresponding new taxon flag is not set

**Comment by jlegind** [comment]
The taxon rank name is now recorded.

**Comment by FedorSteeman** [comment]
The method for retrieving and recording taxon rank name `get_rankname` throws an error when entering a new taxon. 

![image](https://user-images.githubusercontent.com/10909008/236818335-6d488982-767d-4097-92e6-a30d7cb1a35f.png)

This is also not to best way to solve it. The taxon rank can be resolved from the autosuggest box, which is the information expert here.

**Comment by PipBrewer** [comment]
Myself and Bhupjit have been unabvle to reproduce this issue
