### ISSUE TITLE
Write end-to-end tests

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#325]
There is a page for end-to-end testing here:
https://github.com/NHMDenmark/Mass-Digitizer/blob/main/tests/Usability_test_procedure.md

We have settled on the term end-to-end testing instead of usability testing.

**Comment by jlegind** [comment]
I have a page for function testing here: 
https://github.com/NHMDenmark/Mass-Digitizer/blob/main/tests/Functional_test_procedure.md

**Comment by FedorSteeman** [comment]
Great start! But I think they need to be more extensive and some example data to test with.

**Comment by FedorSteeman** [comment]
I'd say every instance where we discovere(d) a bug should be made into a functional test including sample data.

**Comment by PipBrewer** [comment]
@jlegind to update this with results of functional tests

**Comment by jlegind** [comment]
The end-to-end testing document has gotten some minor updates today. Mainly around the multi-specimen/-object radio button functionality.

**Comment by PipBrewer** [comment]
@bhsi-snm Should we close this? There doesn't appear to be much action on this.

**Comment by bhsi-snm** [comment]
sure @PipBrewer
