### ISSUE TITLE
Adapt GREL script (+ guide) to take heed of novel taxa's inferred rank 

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#327]
The post-processing script should take heed of how the app currently infers the rank of novel taxa based on the following logic: 

```
elementCount = len(taxonNameEntry.strip().split(' '))
subgenusCount = 0
if '(' in taxonNameEntry: subgenusCount = 1

if ' var. ' in taxonNameEntry: rankid = 240
elif ' subvar.  ' in taxonNameEntry: rankid = 250
elif ' f. ' in taxonNameEntry: rankid = 260 
elif ' subf. ' in taxonNameEntry: rankid = 270 
elif elementCount == 3 + subgenusCount: rankid = 230
elif elementCount == 2 + subgenusCount: rankid = 220
elif elementCount == 1 + subgenusCount: rankid = 180
```

The guide should also be updated to make sure that digitizers adhere to this format: 
* Genus (Subgenus) species (' var. '/' subvar. '/' f. '/' subf. ') 

Tasks: 
- [x] Adapt GREL script to take heed of above rank inference 
- [x] Adapt guide to make digitizers adhere to fixed format

**Comment by jlegind** [comment]
Other GREL issue: #411
