### ISSUE TITLE
Discuss possibilities for including species catalogue numbers to taxon spine for NHMA

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#336]
NHMA currently has the species number from a catalogue on the front of their specimen drawers. Discuss the possibilities and implications for designing and implementing this in the app before deciding whether to go ahead with the work.

**Comment by jlegind** [comment]
Level of effort: 'Easy'.

**Comment by PipBrewer** [comment]
Now issue #348
