### ISSUE TITLE
Mark synonyms before merging/moving

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#343]
How to deal with synonyms in digitisation and in Specify

**Comment by PipBrewer** [comment]
We expect to encounter synonyms / old names etc during the digitisation process, for example on old specimen labels. It is useful information to know what name has been associated with a specimen in the past, regardless of whether that name is valid or currently accepted. A digitiser is not expected to have the expertise to recognise these, nor are they expected to associate them with a current name. This should be done in Specify. Therefore, when building a taxon spine, we should ensure to link synonyms and other names with their current name in Specify (there should be a column added in the taxon import sheet). This means that when a synonym is associated with a specimen as a determination, it is also linked with the currently accepted name. @FedorSteeman does this seem like a sensible way to proceed?

**Comment by FedorSteeman** [comment]
Yes, this is already supported by Specify. Including synonyms in the taxon spine will enable this. We could perhaps mark them as synonyms, but when typing in the name in the app, it will just be one of the suggestions nevertheless.

**Comment by PipBrewer** [comment]
Closing issue based on above info
