### ISSUE TITLE
Parse new hybrid names

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#346]
**Describe the bug**
Due to the name being three or more string tokens - the rank is of hybrids will be incorrectly assigned.

**To Reproduce**

1. create a Digi app record with a new hybrid name
2. save the record and check the SQLite DB specimen table

**Expected behavior**
Either:
The app should recognize hybrid names and treat them as such: Rank assigned should be species.
Or:
Post processing GREL script should be updated to handle novel hybrid names.

Software version:

[Mass Digitization App version 1.1.24](https://github.com/NHMDenmark/Mass-Digitizer/releases/tag/v1.1.24)
Tested on Windows 10 Enterprise - Version 10.0.19045 Build 19045

**Comment by jlegind** [comment]
Effort level: 'Easy'
