### ISSUE TITLE
NHMA taxonomy plan

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#348]
Create a plan for converting the Aarhus taxonomy which is ID based into something that can supplement the existing Digi App taxonomy spine.

It is relevant because Aarhus does not have the resources to redo their drawer labelling from taxon numbers to the actual taxon.

The effort required is in the range of one or two weeks.

### Plan/solution:
The goal is to make it easy for the NHMA digitizers to input a number rather than a name in the taxonomic section of the app. There should be a small input field next to the 'taxonomic name' input field where the ID ("Sortnr.") can be typed. This field should only become visible to NHMA Entomology collection users. Upon completion of the ID input a label with the taxonomic name should appear in the taxonomic name field in the form itself. This is a small check on the ID typed.

#### What is the expected acceptable result?

There should minimum be an option of inputting the NHMA taxon ID into the App which resolves to a taxon name. The resulting DB record should have the following columns in addition to the ones already in the specimen table:
'sortnr' (NHMA taxon ID)
'rubin' (?)

**Comment by jlegind** [comment]
This issue awaits a chat with Ole Karsholt about some of the weird columns.

**Comment by PipBrewer** [comment]
Additional info from Thomas Simonsen (NHMA) about the info on the front of pinned insect drawers

[SV_ Taxon numbers.pdf](https://github.com/NHMDenmark/Mass-Digitizer/files/12238691/SV_.Taxon.numbers.pdf)
[KArsholt  Nielsen 2013.pdf](https://github.com/NHMDenmark/Mass-Digitizer/files/12238695/KArsholt.Nielsen.2013.pdf)

**Comment by jlegind** [comment]
If user is logged in under NHMA then the Aarhus taxonomy becomes active and the taxonomy input field will expect numbers.
That is my suggested solution.

**Comment by jlegind** [comment]
The transformed NHMA spreadsheet produces 4415 records similar to this:

{'sortnr': 4404, 'superfamily': 'Noctuoidea', 'family': 'Nolidae', 'genus': 'Nycteola', 'species': 'degenerana'}

**Comment by jlegind** [comment]
Needs a taxonomic lookup to get the spid. Coming soon.

**Comment by jlegind** [comment]
The processed NHMA taxonomy records have been verified against the original spreadsheet.
+
There is now a table in the SQLite DB called NHMAjoin which contains the full taxonomic record as well as the spid ID which we will need to look up the name itself in the DaSSCo taxonomy table (taxonname).

**Comment by jlegind** [comment]
NHMA Entomology taxonomy has been converted to regular records.

**Comment by jlegind** [comment]
Code til at normalisere taxonomien: 
https://github.com/jlegind/code/blob/master/nhma_taxonomy.py

**Comment by jlegind** [comment]
Please be aware that the "Aarhus_Dk_lepidoptera2013.xlsx" file and its derivatives are not reliable. See issue #407
