### ISSUE TITLE
Naming convention for digi app export files

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#349]
# Template for isues/tickets in DigiApp
##  What is the issue ?

```
We need a naming convention for the digitisers to follow when exporting records from the digi app each day.

```

## Why is it needed/relevant ?
```
A digitiser may export more than one batch of records from the digi app each day. At the moment there is no file naming convention for these export files and so it is difficult to tell if these are duplicates. We already have examples of exports from the same person on the same day - all with different types of suffixes. It is very confusing. Are they separate files, duplicates, issues etc?

```
## Estimate level of effort required.

```
Easy


```

## What is the expected acceptable result.

```

- [ ] Decide an acceptable convention
- [ ] Communicate this to Chelsea (and ask her to incorporate into workflow training and mention on AD Slack)
- [ ] Incorporate into documentation procedure on Github

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by jlegind** [comment]
Matilde has accepted my suggestion-

A solution could be; [collection name] like NHMD_Herba_, then the [date] (yyyymmdd_). Then [hours_minutes_] and initials .

Example:
NHMD_Herba_20230621_14_05_MG.csv
