### ISSUE TITLE
Sort out folder names for dataset exports

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#350]
Path: N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data  
  
Suggestion:  
After a file comes into the `path/Exported_from_app_data_files` and the file is picked up by the data manager, it needs to be transferred into the `Exports_in_process` sub-directory to facilitate tracking of the process. It is desirable to have the `Exported_from_app_data_files` directory almost empty which tells us the datasets that were exported are being post-processed and imported into Specify.

After post processing the dataset is moved into 'PostProcesed_NOT_been_imported'. This is to be able to 'go back' for each step in the process for debugging reasons.  

After the post processed dataset is imported into Specify it is moved into the  `imported_into_specify_datasets` which exists in the 'Path' directory.  
When I write files are 'moved' I mean that they are cut and pasted so that files are not replicated all over the directory structure.

**Comment by jlegind** [comment]
Import protocol has also been updated.
https://github.com/NHMDenmark/Mass-Digitizer/blob/main/documentation/import_protocol.md

**Comment by PipBrewer** [comment]
Finish updating folders with Matilde's corrected spreadsheets - checking they are in Specify, moving to correct folder and deleting unwanted folders

**Comment by jlegind** [comment]
My immediate solution would be [collection name] like NHMD_Herba_, then the [date] (yyyymmdd_). Then [hours_minutes_] and initials .
Example:  
NHMD_Herba_20230621_14_05_MG.csv

**Comment by jlegind** [comment]
Matilde agreed to the proposed format above.

**Comment by PipBrewer** [comment]
@jlegind There still seems to be unwanted folders in the Data folder on the N Drive (for imports)

**Comment by jlegind** [comment]
I did a thorough clean up and double checking of the redundant folders and their files. Those folders are gone now.

**Comment by jlegind** [comment]
There is a 'Capture_one_test' directory which contains many .tif files. I decided to leave this one alone.
Also there is a temp folder which I use for checking file structure by saving suspect csv exports as Excel files which yields a quick overview over content and columns. Is there data missing? Do all records have the correct number of columns?
