### ISSUE TITLE
Check app storage locations against Specify for NHMD vascular plants

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#355]
The name of the collections in the storage tree has been edited in Specify for NHMD Vascular plants. Please check the App DB and Open Refine scripts and update.

- [x] Tweak the openRefine script to comply with the new institution name (App version 1)
- [x] Create the openRefine script ready for the next App version 
- [x] UPDATE THE db editions/NHMD storage taxonomy file to reflect Specify change.

**Comment by jlegind** [comment]
All three items are completed and this part of the app is ready for production.

**Comment by jlegind** [comment]
Box collection name is: C-Danish Herbarium
Shelf is: C-CP Danish Vascular Plant Collection

**Comment by PipBrewer** [comment]
Added to https://github.com/NHMDenmark/Mass-Digitizer/issues/543 instead
