### ISSUE TITLE
Verify that catalog number/barcode is validated depending on institution/collection.

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#356]
The App must be prepared to take an institution name and a collection name and set a validation length on the barcode based on this combination.  
~~- [ ] Prepare for institution and collection name validation length~~
Collection name already has the institution initials prepended which makes further inquiries unnecessary.

The catalog number submitted must be 8 digits **in case of 'NHMD Vascular Plants** and have no alphabetic characters. 
The catalog number submitted must be 9 digits **in case of 'NHMD Entomology** and have no alphabetic characters. 
Please implement in specimen_data_entry.py in "event == 'inpCatalogNumber':"

**Comment by PipBrewer** [comment]
This was already implemented and so we need to figure out why this is no longer the case.

**Comment by jlegind** [comment]
> This was already implemented and so we need to figure out why this is no longer the case.

The requirement from Specify is now nine digits. I need to take care of this in postprocessing for the files generated using app version 1.1.0
In version 1.1.1 the catalog number will be padded to make the nine digit requirement.

**Comment by jlegind** [comment]
If there are hard rules that the collections have uniform barcode formats within each collection, then this task becomes easy.
Otherwise it is a difficult one.

Currently there are two solutions:
ONE: Validation on barcode length presuming above condition.
TWO: All barcode readers are set to append a return character to the end of the barcode. This allows for greaterThanOrEqual validation or repudiation of failed reads that return a barcode less than the expected length.
