### ISSUE TITLE
NHMA variety fullnames don't have "var." in them

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#363]
The taxon tree in the NHMA Specify database for entomology does not have "var. " in the fullname for varieties for some unknown reason. This causes problems in the app, which expects this. This probably needs to be changed in the NHMA db and then transferred (synchronized) to the taxon spine in the app. We need to ask NHMA if this is OK.

**Comment by bhsi-snm** [comment]
ask @PipBrewer to give priority. she knows

**Comment by PipBrewer** [comment]
I only made the comment into an issue, so this was not originally from me. @FedorSteeman Do you know how NHMA currently puts varieties into Specify?

**Comment by PipBrewer** [comment]
The workflow at the moment is that the full trinomial is put into the taxon field and selected. The digitiser goes back and types in var. in the correct place. This will create a new taxon (if it isn't already in there), with variety as the rank. On import to specify, it should add the variety taxon record, with "var." removed.

**Comment by PipBrewer** [comment]
@FedorSteeman Based on the current db and GREL script, there is no reason why we shouldn't be able to add "var." to NHMA names in future if we want them with no additional development?

**Comment by FedorSteeman** [comment]
There are currently only three taxon of rank variety in the entire NHMA database. 

It would be a problem for the GREL script to deduce rank if " var. " is not in the taxon fullname as supplied by the app.

**Comment by FedorSteeman** [comment]
And the taxon fullname in the app is taken from Specify db, so by adding " var. " to those fullnames there could make the whole thing work.

**Comment by PipBrewer** [comment]
@FedorSteeman Thanks. The protocol would be the same - the digitisers would add var. to them name in the app. Just checking  that there is no reason why this would not work specifically for NHMA as suggested by the title of this issue. If we expect it to work (either adding var. records to Specify and drawing to app, or for new names put directly into the app, we can add them to Specify during workbench import), I will just close this issue.

**Comment by FedorSteeman** [comment]
I predict that, unless the fullname in the app includes the " var. " string, that these taxa entered with it will be marked as new taxa. 

I would suggest adding the string to the fullnames in NHMA.

**Comment by FedorSteeman** [comment]
I'll take a final look at this and then it can probably be closed.

**Comment by FedorSteeman** [comment]
So "var." is still not part of the full name in the NHMA Entomology taxon tree, and I clearly still need to crank up Specify6 to change the relevant settings. 

However, looking more closely at this, it is rather odd we even have these cases. 
The only varieties that are present in the NHMA tree at all are the following bumblebees: 

- Bombus pascuorum var. mniorum
- Bombus pascuorum var. pascuorum
- Bombus pascuorum var. tricuspis

According to [this checklist](https://vildebier.dk/filer/madsen-calabuig_2012.pdf) that has @DanBIF Isabel as co-author, these are subspecies: 

![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/848ceceb-bf8b-4b11-8c53-a5af2ccce85f)

Could there have been a mistake?

**Comment by FedorSteeman** [comment]
Anyways... The "var. " string is now part of the fullname for varieties in NHMA Entomology: 

![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/6737942d-c314-4d7f-86da-34f613487feb)

https://specify-nhma.science.ku.dk/specify/view/taxon/8286/ 

This will ensure a proper import.
