### ISSUE TITLE
NHMD Entomology - Storage Locations

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Mass-Digitizer#365]
# Template for isues/tickets in DigiApp
##  Storage Locations do not appear to be loaded in the MADD app for NHMD entomology

```
# Detailed description of the issue. 
# It could include examples,reference to similar issue and clear boundaries of the issue.

# The drawer level storage locations of insects in dry storage are not preloaded in the app


```
## It could be helpful to have drawer level location information

```
# Explain the need, relevance.
# Give scenario(s) of why and when this could be relevant. 

```
## Estimate level of effort required.

```
# easy
# difficult
# hard

```

## Optimal would be drop-down options for the drawer level location information

```
#  How to approach it?
#  Give a clear approach/potential solution on how to resolve it.
#  What steps would be required to do this ?
#  It might also be an idea to put some pseudocode if relevant.

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by jlegind** [comment]
NHMD Entomology has these storage values:
Lepidoptera DK (Pinned)
Non-Lepidoptera DK (Pinned)
Transit Entomology (Pinned)
