### ISSUE TITLE
NHMD Entomology - Connecting pinned insects with slides prepared from the same specimen

### ISSUE THREAD

**Issue by chelseagraham** [NHMDenmark/Mass-Digitizer#367]
# Template for isues/tickets in DigiApp
## There are multiple preparations for many specimens within the NHMD entomology collections. 

```
# Detailed description of the issue. 
# It could include examples,reference to similar issue and clear boundaries of the issue.

# Many of single lepidoptera specimens are dually represented on pins as well as on slides that have been prepared of their geintalia. When a slide has been prepared from a pinned specimen, a label indicating this is present on the pin. This label contains the slide number. It is not clear if the slide number corresponds to an overall collection of slides for entomology, or if slides are renumbered for subcollections. Jan Pedersen mentioned that Ole Karsholt would know. 


```

## Why is it needed/relevant ?
```
# Explain the need, relevance.
# Give scenario(s) of why and when this could be relevant. 

# Collections managers prefer that the slides and insects have the same catalog number. It would be optimal to be able to register the existence of the slide in the MADD App. 

```
## Estimate level of effort required.

```
# easy
# difficult
# hard

```

## A standard is set of a box to check or terminology to use to indicate the slide which corresponds to the pinned insect.

```
#  How to approach it?
#  Give a clear approach/potential solution on how to resolve it.
#  What steps would be required to do this ?
#  It might also be an idea to put some pseudocode if relevant.

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by jlegind** [comment]
Bhupjit: "There should be a separate issue for how the 'notes' field is used regarding the multispecimen solutions for previous versions of the app."

**Comment by jlegind** [comment]
Bhupjit: "There should be a separate issue for how the 'notes' field is used regarding the multispecimen solutions for previous versions of the app."

**Comment by PipBrewer** [comment]
The slide would have a separate barcode if a separate record in Specify, or a repeated barcode if in the preparations table. This is the choice of collections managers. If there is a separate record this is a multiobject specimen and they would be linked via container. If they are a preparation, we would need a way to be able to insert into this table as part of mass digitisation. My suggestion is to create a separate record in Specify and link with a container. This is what we are doing in Botany. Would need a way to record in the app the specimen number it is linked with to create a container to link with existing records.  This will involve a slight modification of the app. @chelseagraham will need to follow up to decide what the preferences are, report back here so we can schedule the work.

**Comment by chelseagraham** [comment]
During our October 25th Entomology DaSSCo Digitization Catch-up meeting, the group agreed amongst each other that they would like the slide to be saved in the database as a preparation of the pinned insect, just as any other type of preparation.

One idea could be to incorporate an ‘Associated Preparation’ check box and or/create a controlled vocabulary to enter into the Notes field to link the slide number, or any other record of a preparation type associated with the individual.

**Comment by PipBrewer** [comment]
@chelseagraham This is a lower priority as we haven't got to slides yet - but just to say, we currently have no way of easily doing this (inserting into the preparations table). In addition, as the preparations don't have sub-numbers, it is not easy to isolate which line in the preparation table should even be updated. I would suggest we look at this when we get to slides and not before. In the meantime, technically, things like this may be more difficult to implement than they appear.

**Comment by chelseagraham** [comment]
So, we don't need to worry now about connecting the information yet? When we get to digitizing the preparations, we will refer back to the physical collection to obtain the barcode numbers associated with the individuals and therefore the preparations?

**Comment by PipBrewer** [comment]
@chelseagraham How do we know that a specimen we digitise has an associated slide?

**Comment by chelseagraham** [comment]
From today, 30 January, Digitizers will (per issues log entry No. 40) Attribute one barcode to the pin. Click the radio button for MOS in the Digi app. Write in the notes field "Associated Preparation Slide #_" for example "Associated Preparation Slide #3" Jesper has created a data matrix with this controlled vocabulary. 

@PipBrewer Astrid and Jesper are wondering if creating a container via clicking MOS is correct

**Comment by chelseagraham** [comment]
Astrid has provided these images to illustrate how the labels look that indicate a slide has been cretaed

![IMG_4701](https://github.com/NHMDenmark/Mass-Digitizer/assets/108529653/cbae6d1e-6fdd-4b4a-8c64-ee460747468b)
![IMG_4702](https://github.com/NHMDenmark/Mass-Digitizer/assets/108529653/39854e9e-b0c7-4021-a283-c4ea3613d376)

**Comment by chelseagraham** [comment]
From yesterday, 13 March, Digitizers will (per update on issues log entry No. 40) Attribute one barcode to the pin. Write in the notes field "Associated Preparation Slide #_" for example "Associated Preparation Slide https://github.com/NHMDenmark/Mass-Digitizer/issues/3" Jesper has created a data matrix with this controlled vocabulary.
