### ISSUE TITLE
Set collection alternative taxonomic identifiers from Specify

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#380]
##  What is the issue ?
To make a maintainable and simpler workflow from the identifier based taxonomy and to the Digi App taxonomic alternative NHMA Entomology table.

# Detailed description of the issue. 
The current solution is based on a static document. Having Specify as the source for the alternative taxonomy makes it easier to track updates to this taxonomic system. We will have regular taxonomic updates to the App and these will include alternative identifier changes.

## Why is it needed/relevant ?
For long term maintainability.

## Estimate level of effort required.
Medium

## What is the expected acceptable result.
Should the next taxonomic update contain updates to the alternative taxon identifiers, then it will not upset the existing workflow which sets up the tables that the App relies on.

##  Give a clear approach/potential solution on how to resolve it.
The alternative taxonomic identifiers are added to a separate field in the 'taxonname' table.
From here they are extracted to the lookup table for the NHMA situation along with the attendant taxonomic name.
##  What steps would be required to do this ?
There needs to be a new taxonomic export from Specify.

## What could be the challenges ? 
Identifying novel alternative taxonomic identifiers.

## What test are required ?
A comparison of the tables from the current solution and the solution described here.

## What documentation required?
A description of how to employ the .py file.
Update the https://github.com/NHMDenmark/Mass-Digitizer#preparing-database-file-for-bundling documentation to handle the alternative taxon identifier table.

**Comment by PipBrewer** [comment]
The taxonids were derived from Specify as per #373 (https://github.com/NHMDenmark/Mass-Digitizer/commit/0d0beba958abcf787a769503c7168834380b5c3f on 07/09/2023)
