### ISSUE TITLE
Barcode field is (incorrectly) accepting non-numeric values

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#386]
Barcode field should only accept numeric values (8 digits for NHMD vascular plants, 9 digits for NHMA and NHMD Entomology). Currently accepts non-numeric values:
![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/94843484/52f56cfb-f9fc-4a09-a4a8-587439003106)

**Comment by jlegind** [comment]
Fixed by implementing validateBarCodeDigits() and validateBarCodeLength()
