### ISSUE TITLE
Automatic saving of record on beeping barcode not working

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#389]
The app was supposed to have implemented automatic saving after beeping in the barcode (so you don’t have to press enter). That is not the case at the moment.

**Comment by FedorSteeman** [comment]
Can no longer replicate. Presumed fixed.

**Comment by jlegind** [comment]
The issue must have been fixed with the programming of the barcode scanners where a new-line character is added to the end of the scan. The code picks up on the new-line and saves at that point (after cleaning out the new-line char).
