### ISSUE TITLE
Inconsistent values in specimen table for object condition

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#390]
I’m not yet sure why but “False” has suddenly started to be input into the specimen table in the db under object condition:
![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/94843484/d829bd4e-5405-4620-bddc-cc0c3cc5ba00)

**Comment by FedorSteeman** [comment]
Can't replicate. Presumed a transient problem going from commit https://github.com/NHMDenmark/Mass-Digitizer/commit/e3e6e96e856bae75ef72ccbb7ab36c0d91d8576f

**Comment by jlegind** [comment]
The string "Needs repair" is added for records having Damaged specimen checked.
