### ISSUE TITLE
Incorrect radio button and container behaviour when navigating earlier records

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#391]
When I go back and change from MSO or MOS to single specimen all is fine. However, when I move to the next record in the sequence which had the MSO or MOS it now has the container name in it, but it is “single specimen object” which is selected in the UI. See below:
![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/94843484/8f1ba400-431b-4923-9aa3-c9375f3b6b02)

**Comment by FedorSteeman** [comment]
Tested and apparently fixed.
