### ISSUE TITLE
Previous pane partly selectable in UI

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#392]
You can now select the preview pane (we disabled this feature), but it doesn’t populate the details into the main pane. This should be disabled. Preview pane is for reference only.

**Comment by FedorSteeman** [comment]
Fixed with commit https://github.com/NHMDenmark/Mass-Digitizer/commit/e8edd0ec6bdf142af14e1594817ee76c0b2ef209 by setting select mode to "none" for previousRecordsTable.
