### ISSUE TITLE
Record saved without entering new barcode

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#394]
If I press save multiple times without entering anything new, it copies barcode from previous records and creates a new record.

**Comment by FedorSteeman** [comment]
Can't replicate. Presumed fixed.

**Comment by bhsi-snm** [comment]
duplicate of #395

**Comment by jlegind** [comment]
Fixed by implementing validateBarCodeDigits() and validateBarCodeLength()
