### ISSUE TITLE
Forward button glitch

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#395]
If I press save multiple times without entering anything new, it copies barcode from previous records and creates a new record

**Comment by FedorSteeman** [comment]
Can't replicate

**Comment by FedorSteeman** [comment]
Presumed fixed.

**Comment by bhsi-snm** [comment]
the title forward button glitch doesn't correspond to the explanation of the issue. 
was is correctly understood and corrected?
