### ISSUE TITLE
Issue with container of specimen in Specify from DaSSCo import

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#399]
Matilde identified the following issue: "So today we encountered a MSO while photographing, that only had one barcode: 0082831. We gave it an additional barcode (00928826) and flagged it as a MSO (MSO486765941051266). Can you connect the two of them? " 

Fedor had a quick look in Specify and reported the following "Now that I look at the container data I see something wrong with it. For some reason the type isn't set (MOS or MSO)." This needs investigation and then we need to look at other similar workbench imports.

**Comment by jlegind** [comment]
Dear team, the records submitted by Matilde, Serena, and Jens all have the properly formatted container IDs. (232 records with container ID total)
See attached sheet.
[query_results_2023-09-15Test.xlsx](https://github.com/NHMDenmark/Mass-Digitizer/files/12616936/query_results_2023-09-15Test.xlsx)

**Comment by FedorSteeman** [comment]
Note: Those records imported earlier with containers associated, did not have the container type set. I have manually fixed those cases in the database and advised to adjust his mapping so container type is also transferred. 

I also found that one of the records in question had not been imported. As soon as that is done I can connect the two records with the new container created by Matilde and co.

**Comment by PipBrewer** [comment]
I am looking into this (as we will need a general procedure for this and I think that this is not a DigiApp issue, but a workflow issue); however, the number quoted (0082831) must be incorrect. I therefore need to look at the image of the sheet associated with 00928826 to get the correct other barcode. I have messaged @chelseagraham on slack. This depends on her having entered this information into a spreadsheet (where is this located, the one for Thomas's test data set). We have a general issue that renaming the images with a GUID makes it hard to trace them back if something goes wrong or there is a delay importing them.

**Comment by chelseagraham** [comment]
The spreadsheet for Thomas' test data set is located here: 
N:/SCI-SNM-DigitalCollections/DaSSCo/Pilot Data/Herbarium Working Data/QAQC_cg/QAQC_cg.xlsx

I don't see the record for this sheet in the spreadsheet. That means it either wasn't a part of the data set (I think it was later than the set studied), did not flag any concerns, or was missed. 

If we know the date they were entered into the app, we can look at the images folders from around that date (There is not necessarily a correspondence from the date entered and the date imaged).

**Comment by PipBrewer** [comment]
@chelseagraham This was emailed to me on 13th September. We need to make sure there is complete recording of these issues with specific details and checking details are correct. We need to check them as soon as we see them in the issues log, to see if additional details are required before people forget.

Would it be possible to get someone to identify the relevant image and save a jpg version and drop it in this issue?

**Comment by PipBrewer** [comment]
@thomas is making jpegs of the existing images. Once this is done, could someone find the relevant image and let me know?

**Comment by ThomasAlscher1991** [comment]
The jpeg conversion is still running. If somebody could tell me which date the sheet in question was digitized, I can prioritize the conversion for this folder.

**Comment by RebekkaML** [comment]
![7e7-9-0d-0f-26-11-0-001-00-000-06b8eb-00000](https://github.com/NHMDenmark/Mass-Digitizer/assets/144137243/30e74471-f7f9-430f-8f2a-444fb550c2ba)

**Comment by RebekkaML** [comment]
The corresponding export file has been checked and moved to 1.Exported files from App for importing into specify. Once this is done, the specimens can be connected to the correct MSO there.
@jlegind, can you let me know when this file is in Specify? Thanks!

[NHMD_Herba_20230913_15_55_RL_corrected.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/14050429/NHMD_Herba_20230913_15_55_RL_corrected.csv)

**Comment by RebekkaML** [comment]
containername MSO486765941051266 has been added to specimen 000928315 in Specify. It is now correctly linked to 000928826.
