### ISSUE TITLE
Objectcondition "Needs repair" not cleared in subsequent records

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#400]
Reported by @PipBrewer & @jlegind: "Once you check the Damaged Specimen tick box in the UI and save the record, the tick mark is unchecked for the next record, but it persists in the database with “Needs repair” appearing in subsequent records in the specimen table. If you go back in the UI, you can see that the check box has actually persisted. This goes for NHMD and NHMA."

**Comment by FedorSteeman** [comment]
The way the data entry form is set up for a new record during saving was deviating from the MVC pattern: It no longer instantiated a new instance of the specimen model, but re-used the current instance, yet failing to clear all fields. It's been brought back to the original method of creating a new instance and transferring sticky field values to that instance.

**Comment by jlegind** [comment]
Specific fix code:
`newRecord = self.collobj.id == 0`
...
...           
              `# If so, prepare for new blank record  `
              ` if newRecord:
                    # Create a new, blank specimen record (id pre-set to 0)  `
                   ` self.collobj = specimen.Specimen(self.collectionId)  `
