### ISSUE TITLE
Clearing the full taxon name does not erase other taxon data

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#402]
# Template for issues/tickets in DigiApp
##  What is the issue ?

```
If you have taxon names and save some records. 
On deletion of records, the taxon name and scan barcodes in, retains some of the taxon info in the local app 
db specimen table, but not all of the info (see records 47-49 in below screen shot for which the taxon name 
was empty in the UI). Tested for NHMA and NHMD.
```

<img width="452" alt="image" src="https://github.com/NHMDenmark/Mass-Digitizer/assets/135235678/f3728e6c-131e-400b-a37b-5f0418d2fe73">

### Context
If this issue is not resolved, records containing errors might be left in the DB and if imported into Specify would be much harder to identify and remove.
### What is the expected acceptable result.

```
it should clear the db row completely on record deletion
```

**Comment by FedorSteeman** [comment]
It does now

**Comment by jlegind** [comment]
The acceptable behavior: `it should clear the db row completely on record deletion ` has been implemented and tested.

**Comment by FedorSteeman** [comment]
There is some contradiction between the ticket title and description. The issue was taken to be that clearing the taxon input field, should also clear all related taxon data fields, but not the entire record. As Jan stated, it is not possible to delete records. Please note that this has never been a requirement yet.

**Comment by bhsi-snm** [comment]
I agree, there is a small but important distinction between deleting the record and clearing it.
Is there a way to handle partially empty records in GREL script ?? 
I agree, deletion is not part of DigiApp functionality, but @PipBrewer, what is the ideal behaviour, this issue is reflectioin of your testing working done along with Jan(via the doc that you circulated)?

**Comment by FedorSteeman** [comment]
Clearing the taxon name should only clear taxon-related data and not the entire records. 

I doubt this will pose an issue for the PostProc script.

**Comment by PipBrewer** [comment]
Just spoke to Bhupjit. He was particularly worried about importing data to Specify with little to no information other than barcode. I explained that that is not an uncommon situation in collections.
