### ISSUE TITLE
[ISSUE] Taxon number field requires [enter] press

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#403]
# Template for isues/tickets in DigiApp
##  What is the issue ?

```
In NHMA when you enter the taxon number, it should automatically populate the 
taxon field (as a check), but right now, it requires enter to be pressed to populate the taxon field.
```

## Why is it needed/relevant ?
```
It provides a check and make sure, taxon field has the corresponding value to the
 taxon number 
```

## What is the expected acceptable result.

```
It populates the taxon field on edit in the taxon number field, instead of pressing enter.
```

# What could be the challenges ? 

```
if it cannot find the taxon name, how should that be handled ? 

it could be nice to check that it works both ways
```

# What test are required ?

```
enter the number and see if it populates the taxon field

```

**Comment by FedorSteeman** [comment]
Appears to be fixed with commit https://github.com/NHMDenmark/Mass-Digitizer/commit/438e83193fb9c71b3707d06844e94c20ae27ed08

**Comment by jlegind** [comment]
It isn't really possible to have this function of auto-filling the taxon name field since the taxon ID can be anything from one digit to six digits. There is no way to guess when the number has finished inputting except by making it explicit with an Enter.

**Comment by jlegind** [comment]
Only pre-determined fields can have auto-fill and auto focus behavior.
