### ISSUE TITLE
Partial barcode visual when scanning -needs better explanation to replicate

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#408]
###  What is the issue ?

I cannot reproduce this issue in the 1.1.9 version of the App.
The barcode scan will auto-save the form which triggers non-sticky fields to be cleared. Catalog number is one of those fields.
The barcode can be seen in the post-view table at the bottom of the app form.

**Comment by PipBrewer** [comment]
When scanning barcode into relevant field in UI, sometimes it would not show the digits. I could not see them. This was during testing an earlier version. It sounds like this has been accidentally resolved) i.e., not by any specific work, may have been a temporary bug specific to that version, or my computer was playing up at the time. I will close the issue with this in mind.
