### ISSUE TITLE
Update release notes for 1.1.18 to fully reflect all changes to app

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#429]
Template for isues/tickets in DigiApp
What is the issue ?

# Detailed description of the issue. 
# It could include examples,reference to similar issue and clear boundaries of the issue.

When a new version of the app is released, the release notes should represent a full change log of all changes since the last release and reference the ticket numbers

Estimate level of effort required.

easy

What is the expected acceptable result.

Every issue in Github since the last release is checked and referenced.
The text should be clear and concise and should make sense to non-technical people.

What could be the challenges ?
Changes should be clearly communicated.

What test are required ?

New tests/Could include reference to the existing test
What documentation required?

Could refer to existing documentation and changes in relevant doc files.
Remarks

**Comment by FedorSteeman** [comment]
Link to the release in question:
https://github.com/NHMDenmark/Mass-Digitizer/releases/tag/v1.1.18

**Comment by jlegind** [comment]
I have added the GREL script version to the release notes.
