### ISSUE TITLE
NHMA - Taxonspid is not carried over from the App and into the specimen table

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#430]
**Describe the bug**
NHMA: When using the alternative taxonomic identifier to apply the taxon name the taxonspid is always 0 (numerical zero) in the specimen table. This goes for all ranks.

**To Reproduce**
1. Launch Digi App and sign in as NHMA
2. Use the taxonomic ID field to apply the taxonomic name
3. Barcode + Save record
4. Observe the specimen table and see the new record having taxonspid = 0

**Expected behavior**
All names already in the taxonomy irrespective of entry should have the taxonspid property set to a number.

**Please complete the following information:**
 - version is 1.1.18
 - Column taxonspid in specimen is set to 0 on the conditions mentioned above.

**Comment by jlegind** [comment]
moved to for recview

**Comment by FedorSteeman** [comment]
Fixed.
