### ISSUE TITLE
Digi App taxonomic spine documentation should have more detail

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#432]
##  What is the issue ?
The process for compiling the Digi App taxonomy is not sufficiently described. There are a few notes here and there in the N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App directories.
We should have something more comprehensive.

### Detailed description of the issue. 
The creation of the taxonomic backbone is not trivial and deserves its own guidelines.
Let us begin with the Herbarium taxonomy since it applies generally.
The taxonomies contributing to the spine are :

- The herbarium of Danish vascular plants 
- Plants of the World: derived from World Checklist of Vascular Plants: downloadable at http://sftp.kew.org/pub/data-repositories/WCVP/
- TaxonListAAU.xlsx which lives in `N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Herbarium taxon spine\Source files`
- The GBIF backbone taxonomy https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c
- The svampe-checklist was sent by Christian Lange `N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Herbarium taxon spine\Source files`

### Why is it needed/relevant ?
The taxonomic spine provides all the possible names to choose from and is vital to the digitization effort.

## Estimate level of effort required.
Difficult

### What is the expected acceptable result.
A comprehensive list of names that can be discovered in the Danish collections. %100 coverage is not realistic but we can get close.

###  How to approach it?
There needs to be a discussion of which taxonomic sources should have priority. I suggest that locally used taxonomies need to have high priority since these names are likely to be used the most.
Most of the work on the current operational taxonomy was done in a Postgres database and the ease and speed of this tool was satisfactory.

### What could be the challenges ?
Cleaning the source spines and the final product. There will be duplicates and they need to be cleaned out. 

###Is there a potential risk to this. 
We could end up with a taxonomy where certain names will be missing. Users might be annoyed that their favorite names are not there or that the accepted name does not match their evaluation. After all taxonomy is a battleground.

### What documentation required?
A recipe like document describing how a taxonomy is built from multiple sources.

**Comment by bhsi-snm** [comment]
@PipBrewer, I think it would be nice to have a document referred here describing the procedure for building the spine(atleast the part we import into digiapp) for each collection, so that it is document for reference or if incase we want to do it from scratch or do an update.
From above, it sounds like there is a procedure which involves various steps and it might a good idea to mention somewhere saying when this is relevant, for example, updating the spine etc...

**Comment by PipBrewer** [comment]
@bhsi-snm You mean including how to get it out of Specify (you mention updating)? That may involve Fedor.

**Comment by bhsi-snm** [comment]
Sure, I don't think we need to include specify part of it just what we need to do it on our end on DigiApp and steps where we just mention Fedor will do the needful..?

**Comment by PipBrewer** [comment]
All of the above is pretty much done in Specify

**Comment by bhsi-snm** [comment]
okie then we can just close it 👍
