### ISSUE TITLE
Accommodate homonyms in DigiApp

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#434]
# Template for isues/tickets in DigiApp
##  What is the issue ?

```
# Detailed description of the issue. 
Homonyms are supposed to identified during digitsation and they can only be done 
through Author name and Year but currently DigiApp doesnt show that information 
when selecting the taxon name. 
We need to add that so that digitisers can select the right taxonname and identify 
between homonyms.

```

## Why is it needed/relevant ?
```
# Explain the need, relevance.
We are digitising the vascular plants collection which falls under botany. Botany has 
homonyms which means when we are digitising, sometimes we have not corrected
entered the taxon name or potentially we need to be able to differentiate between
the homonym taxon name which specify does via either Specify Id(taxonspid??) or 
through Author name and Year. But as in our current GUI we do not have fields to 
populate that information, digitisers have no way to distinguish between the 
homonyms. So, for homonyms to be incorporated into DigiApp, there are 2 solutions.

- EITHER - it needs to be extended with Author name and Year

- OR Specify API such that we get Specify id based identification of homonyms(I am 
bit unclear, on how that would work so maybe, @FedorSteeman or @PipBrewer
would explain that).



```
## Estimate level of effort required.

```
If we go with Author name and Year it is # difficult
but if we go to integration through API, it is substantial work, 
worth a month (just a guess could be more) .
```

## What is the expected acceptable result.

```
#  How to approach it?
#  Give a clear approach/potential solution on how to resolve it.
#  What steps would be required to do this ?
#  It might also be an idea to put some pseudocode if relevant.

```

# What could be the challenges ? 

```
Is there a potential risk to this. 
Could it affect another part of the project. 
```

# What test are required ?

`New tests/Could include reference to the existing test`

# What documentation required?

`Could refer to existing documentation and changes in relevant doc files.`

# Remarks

**Comment by PipBrewer** [comment]
Information provided by Zsuzsanna Papp is that in Botany, homonyms are common within a family. The original idea was to have a partial taxonomic hierarchy visible to the digitiser (similar to the storage field); however, if they are common within families, this would not resolve this. The solution is to create column(s) for Author and year (remember that commas and brackets etc are important here) in taxon table. This should be visible when selecting taxon in UI. I'm not sure how much of Botany spine has author and year in Specify. May need to get that using GBIF API.

**Comment by FedorSteeman** [comment]
This may take a day or two to implement.

**Comment by FedorSteeman** [comment]
Major issue here is that author information was not added to Specify from the taxonomy source, so will have to be added after the fact.

**Comment by FedorSteeman** [comment]
It is important that this is solved, because it appears that the lack of authorship in the app taxon spine is creating duplicates in Specify upon import in cases where those same taxa do have authorship set. This means that Workbench will not match those taxa and create a new one without authorship. This is bad, because these duplicates will then feed back into the taxon spine of the app db.

One problem with adding authorship to the fullname is that this will screw up the algorithm for guessing taxon rank. Work in progress.

**Comment by FedorSteeman** [comment]
Fortunately, the taxon trees for the two Entomology collections did already possess authorship, and it was easy to transfer those to the app. For NHMD Vascular Plants, the authorship will still need to be added from a source data set. 

Latest taxonomy can be fetched here: https://www.checklistbank.org/dataset/53147/download?taxonID=7707728 

Taking a look at the source for the taxon spine for vascular plants I can see two issues: 
 - The taxonomy that was delivered for import included synonyms, yet these were not marked as such and thus were not imported as such. So currently, synonyms reside on par with accepted names 
 - The taxonomy also includes non-extant taxa, which actually aren't supposed to be in this taxon tree, but rather a (future) digital collection for Palaeobotany 
 - When updating authorship, it will not be possible to distinguish homonyms, but perhaps these can be added later
 
 Plan forward is using SQL to achieve following: 
 1. Update authorship from source taxonomy 
 1. Convert taxa that are actually synonyms into synonyms 
 1. Add any homonyms and other taxa that are not currently in the taxon tree

**Comment by FedorSteeman** [comment]
Just trying and testing in the test db; Updating taxa with author goes fine, but I found my first homonym that evades this effort:
- Chondrorhyncha Lindl.
- Chondrorhyncha (Rchb.f.) Garay

So I need to find a way to add homonyms after the fact, but first I need to drop fossil taxa from the taxonomy...

**Comment by FedorSteeman** [comment]
Unfortunately, GBIF does not mark taxa as extant or extinct in their taxon spine export products. 

However, I have found a way to wrangle OpenRefine to fetch data for each row from paleobiodb. It's just really slow, but progressing: 
![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/e9e4ce20-77cf-4b38-bc81-5962c693db42)

**Comment by FedorSteeman** [comment]
Homonyms are now accommodated by the app, but we need to test whether these actually get through post-processing and into Specify via WorkBench. @jlegind  is tasked with testing this.

**Comment by jlegind** [comment]
A test dataset was created with taxon names plus author name:
```
Delphinium bucharicum Popov
Delphinium carela Buch.-Ham. ex D.Don
Legouixia Van Heurck & Müll.Arg.
Legousia snogerupii Biel & Kit Tan
```

The author name was not processed in the GREL script part of post processing which means that only the binomial was transferred to test Specify.
Example: https://specify-test.science.ku.dk/specify/view/collectionobject/4369407/ 

A solution would be to add an 'Author' column to the Specimen table. This would enable mapping to author name in Workbench.

**Comment by FedorSteeman** [comment]
Although not in itself related to the GREL script, it does make sense, however, that we need the author field in the specimen table so we can map that value in Workbench.

**Comment by FedorSteeman** [comment]
I did not notice that @jlegind created a new ticket #476 for the specific issue that I just fixed within the scope of this ticket. 

I will try to tie these tickets together somehow. 

Tickets will be closed and can be reopened if necessary depending on testing results.

**Comment by FedorSteeman** [comment]
To be tested with pre-release: https://github.com/NHMDenmark/Mass-Digitizer/releases/tag/v1.1.26

NOTE: We have not yet considered the author name of any new taxa...

**Comment by jlegind** [comment]
Comments on "Author names not carried over in the post processed file (GREL)" 476 https://github.com/NHMDenmark/Mass-Digitizer/issues/476#issuecomment-1931523421

**Comment by FedorSteeman** [comment]
Superseded by #476
