### ISSUE TITLE
SUA-SNM-DaSSCo01 account on Laptop in Priorparken DigiApp error on login

### ISSUE THREAD

**Issue by bhsi-snm** [NHMDenmark/Mass-Digitizer#437]
**Describe the bug**

```
The version 1.1.18 of DigiApp gives an error on log in shown in the screen shot
on the common user SUA-SNM-DaSSCo01 laptop in priorparken 

We (me and Fedor) have investigated the error and looked at the line 91 of `collections.py`
``` 
https://github.com/NHMDenmark/Mass-Digitizer/blob/66ad319004a3cd5fdb34cb04b0cf876a7de08fd1/MassDigitizer/models/collection.py#L91
```
It refers to the field 'catalognrlength' and db file has the corresponding field so 
that is not the issue, or potentially the installation is looking at another db file 
potentially located somewhere else in the filesystem
on the further testing by @Matilde Gomes, just to test installed the app on the common account,
she installed it on the PC at priorparken and there was no issue. so its seems to be
only for the specific account on the laptop in priorparken

```

**To Reproduce**

```
Steps to reproduce the behavior:
1. Go to DigiApp and double click on it
2. Select the instituion
3. Enter credentials
4. Select the collection
5. See the error

```

**Expected behavior**

```
A clear and concise description of what you expected to happen.
it should just log in and show the screen to enter specimen data 

```

**Screenshots**

```
If applicable, add screenshots to help explain your problem.

```
![69F759FF-00F1-4AAA-9A29-6E8EC877DD7B](https://github.com/NHMDenmark/Mass-Digitizer/assets/135235678/9085a361-5424-46bd-8b67-5e601c544120)

**Please complete the following information:**

```

 - version -1.1.18
 - behavior in the database - catalognrlength field in collections table maybe related to this issue?
 - specify relation information  - login credentials are verified from specify but might not related

```

**Additional context**

**Comment by bhsi-snm** [comment]
@PipBrewer is it possible to get the pc reinstalled ??

**Comment by chelseagraham** [comment]
> @chelseagraham @nms419 is it possible to get the pc reinstalled ??

What exactly do you mean, Bhupjit? Jesper is out at Priorparken today and could possibly follow specific instructions or give remote access.

**Comment by bhsi-snm** [comment]
I want KU-IT to reinstall the whole thing again.

**Comment by chelseagraham** [comment]
@nms419 On Friday, when you are out at Priorparken, will you please assess this laptop and see if there is any local data that needs to be backed up to the N:/ and then after that, please make a ticket with KU IT to have the operating system reinstalled on this machine? If they won't come to Priorparken to fix it (understandable) Bhupjit may be able to pick it up and bring it to August Krogh one day when he has his car.

**Comment by nms419** [comment]
Local files checked and ticket created with KU IT.
