### ISSUE TITLE
Change the flow around container types

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#439]
If select SSO, MSO or OSM radio buttons, the focus goes immediately to barcode field. However, this should not be the case when just tabbing past these.

The reason for this is that when first log on to App, you will tab through all fields and will do it one after the other. However, during digitisation, you will rarely change much other than taxonomic name (and occassionally broad geographic region), but will often need to select the radio buttons SSo, MSO and OSM and then continue beeping barcodes.

This was requested by MG on 19/10/2023 (via digitisers issue log). CG to raise with other digitisers, collection managers and curators and ask if this is something they would like implemented (although unlikley to be implemented in the next few months).

Regarding the priority of this, need some more information about frequency this happens.

**Comment by PipBrewer** [comment]
This was discussed at the monthly digitiser meeting today (23/11/2023). It was agreed that this would be very useful. I also checked through data files and both MSO and MOS specimens are very common and so it makes sense to implement this. One issue remains: when it is the first record of the day, moving the focus directly to the barcode field could be irritating, as you would then need to go back through the fields in between the two. The solution would be to move the containers to just above the barcode field. This was agreed to be really useful anyway. Everyone at the meeting agreed with the request.

Decision: re-organise the UI so the containers are direcly above the barcode field (and below taxonomic name). This may necessitate (if it makes it easier), getting rid of the division between the green and blue areas on the app (which actually don't make sense anymore).
![container move](https://github.com/NHMDenmark/Mass-Digitizer/assets/94843484/44692df4-5ce0-4323-a28a-98ef49b1b33f)

**Comment by chelseagraham** [comment]
I see no problem with moving the container fields to between the taxonomic name and barcode fields. 
I am checking in with the Digitizers and requested feedback by the end of the day on 7 February. 
Notes is another field that they need to type in at times and which sometimes may alter the flow through the UI.

**Comment by RebekkaML** [comment]
I agree that it makes sense to move the container field. I think it would also make it easier to spot when you forget to uncheck it after an MSO / MOS.

**Comment by JesperMJensen** [comment]
I agree with moving the fields.

**Comment by chelseagraham** [comment]
Based on feedback, it is proposed to move the fields that are not sticky to the same region and keep it colored a brighter, eye catching color as below:
![Picture1](https://github.com/NHMDenmark/Mass-Digitizer/assets/108529653/bd16c014-2ad9-44bd-837a-968a17dcadac)

**Comment by chelseagraham** [comment]
Just chatted with Pip and am adding these notes about alignment of text and fields as well as placement of future radio buttons for Specimen Obscured and Label Obscured
![Picture2](https://github.com/NHMDenmark/Mass-Digitizer/assets/108529653/193bf9f4-f1bb-4695-9d5c-f9ad40ca2901)

**Comment by chelseagraham** [comment]
@FedorSteeman Here are the proposed changes to the UI

**Comment by FedorSteeman** [comment]
@PipBrewer @bhsi-snm Looks clear! Please move to ticket to the right place on the board and I will reach there eventually. 🙂

**Comment by FedorSteeman** [comment]
@chelseagraham What caption should I give the new radiobutton collection "label obscured" & "specimen obscured"? 

Or are these to be checkboxes instead?

**Comment by chelseagraham** [comment]
I think the caption for the radio buttons could just read "Status" or perhaps, "Visibility" @PipBrewer what is your preference?

**Comment by RebekkaML** [comment]
Either the label can be obscured, or the specimen, or BOTH, so we need to be able to check off both boxes if necessary.

**Comment by FedorSteeman** [comment]
Oh I can see this was already mentioned in the ticket dealing with this: https://github.com/NHMDenmark/Mass-Digitizer/issues/445#issuecomment-1943486193 

Let me take it there...
