### ISSUE TITLE
Delete content of notes field after save

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#440]
Requested by MG (via digitiser issues spreadsheet #26) on 19/10/2023.

"Make the app clear the notes field when a barcode is scanned. ATM the note automatically gets copied to next record."

This requires some discussion (other digitisers, collection managers etc) particularly regarding situations when the same note is needed for many records/specimens. 

Also need more information / a break down on how notes fields are being used.

**Comment by PipBrewer** [comment]
After consulting with digitisers today (23/11/2023), I have decided to change the priority of this to 1, as it seems it is needed. Digitisers confirm that it is rare to need to carry across notes from one specimen to another.

**Comment by FedorSteeman** [comment]
So in other words: Notes field should no longer be sticky. Easily solved.
