### ISSUE TITLE
Make object condition visible in Specify production

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#443]
Make object condition visible in Specify production for NHMD VP, NHMD Ent and NHMA Ent. We are mapping to these from the DigiApp and the collection managers and curators should be able to see this field and its values in Specify.

**Comment by FedorSteeman** [comment]
Fixed and committed with https://github.com/NHMDenmark/DanSpecify/commit/1eeccc9311405b2e13954f32ddfe7b5f04712e70
