### ISSUE TITLE
Tick boxes when specimen or label obscured

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#445]
Some discussion has been going on with the collection managers and digitisers, but it looks like we should make a note of instances in the Digi App where the specimens and/or label will not be able to be imaged as they are obscured (has implications for reports to collection managers, status and for transcription). In Specify, I was thinking that if we add them as separate lines in the remarks table using controlled terminology, we should be able to run reports on them to send to collection managers to review. However, in the App it might be easiest to have tick boxes for these. 

- [x] @chelseagraham and Matilde to confirm with Jens S regarding the use of "Specimen obscured" and "Label Obscured" and provide a link here to that ticket with examples of how we use it and why.
- [x] Decide where in UI boxes will go and what will look like
- [x] Hand over to DigiApp team to implement
- [x] Fedor to review the below steps and add additional/edit as needed
- [x] Create tick box in UI for "Specimen Obscured"
- [x] Create tick box in UI for "Label Obscured"
- [ ] Create columns for each of the tick boxes in the specimen table in the db
- [ ] These should then map to separate lines in the Remarks table in Specify and so need to update GREL script (how do we do this?)
- [ ] Fully test
- [ ] Demonstrate to Chelsea
- [ ] Update user documentation
- [ ] Update GREL documentation
- [ ] Update App documentation

**Comment by PipBrewer** [comment]
Sent email on 26/10/2023 to Fedor, Bhupjit and Jan asking whether it is theoretically possible to map notes from DigiApp to different lines in Remarks table in Specify

**Comment by chelseagraham** [comment]
just linking a ticket on the Herbarium board from which I can draw information relevant to this ticket https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/55

**Comment by chelseagraham** [comment]
Current procedures (from @Gomismis document https://github.com/NHMDenmark/Herbarium-Sheets-workstation/issues/55) include

- Flagging a specimen with visible labels and obscured or missing specimens as an **MSO** and scanning a data matrix with the controlled vocabulary "**Specimen obscured**" into the notes field. The number of barcode labels assigned corresponds to the number of visible labels. A single image is taken. (1.2, 1.6, 1.8, 4.1, 4.4)
- Flagging a specimen with obscured labels and obscured specimens as an **MSO** and scanning a data matrix with the controlled vocabulary "**Specimen obscured; Label obscured**" into the notes field. A single barcode is assigned. A single image  is taken. (1.3)
- Entering a specimen with layered specimens and all information on the bottom sheet as a **single specimen** (no radio buttons selected) and scanning a data matrix with the controlled vocabulary "**Specimen obscured; Label obscured**" into the notes field. A single barcode is assigned. A single image  is taken. (1.4, 1.7)
- Entering a specimen with layered specimens and the same label information as a **single specimen** (no radio buttons selected) and scanning a data matrix with the controlled vocabulary "**Specimen obscured**" into the notes field. A single barcode is assigned. A single image  is taken. (1.5)
- Entering a specimen with label obscured as a **single specimen** (no radio buttons selected) and scanning a data matrix with the controlled vocabulary "**Label obscured**" into the notes field. A single barcode is assigned. A single image  is taken. (1.7)
- Entering photos and drawings with associated data and scanning a data matrix with the controlled vocabulary "**Non-botanical object**" into the notes field. The number of barcode labels assigned corresponds to the number of visible labels. A single image is taken. (4.2)

**Comment by FedorSteeman** [comment]
@bhsi-snm  @PipBrewer Are the requirements of this ticket ready for me to start implementing, or who has the ball on this issue?

**Comment by FedorSteeman** [comment]
@chelseagraham What is the status?

**Comment by FedorSteeman** [comment]
@chelseagraham Where on the UI are these two (?) tick boxes to be placed?

**Comment by FedorSteeman** [comment]
Placement specified here: 
https://github.com/NHMDenmark/Mass-Digitizer/issues/439#issuecomment-1934131095

**Comment by FedorSteeman** [comment]
I just talked with @chelseagraham and I believed that these tickboxes are to be mapped to flag fields. However, looking through the ticket specification I can see these are to be mapped to collection object remarks (properties), so will do that instead. 

Teased out the tasks that are relevant to me:  
- [ ] Create tick box in UI for "Specimen Obscured"
- [ ] Create tick box in UI for "Label Obscured"
- [ ] Create columns for each of the tick boxes in the specimen table in the db
- [ ] These should then map to separate lines in the Remarks table in Specify

**Comment by FedorSteeman** [comment]
@chelseagraham Should I group these together as proposed and use the caption "Specimen Flags" as per below? 

![image](https://github.com/NHMDenmark/Mass-Digitizer/assets/10909008/77e33440-3a9b-41b0-b5f0-a16602d922c3)

**Comment by chelseagraham** [comment]
I think this works well. As Rebekka mentioned, they are not mutually exclusive, so the check boxes makes the most sense. :)

**Comment by AstridBVW** [comment]
This ticket was closed prematurely. Steps were missed, there still need to be made changes to the GREL script and mapping to accommodate the mapping of "Specimen obscured" and "Label obscured" to the DaSSCo remarks table in Specify.

**Comment by AstridBVW** [comment]
The GREL script has now been updated and pushed to github. It has been set up in a similar fashion to the notes field with a remark, source and date. The remark is "Specimen obscured" and "Label obscured" respectively, the source is "DaSSCo digitisation", and the date is the same as the cataloged date.

The mapping to the remarks table will be added with the next import.
