### ISSUE TITLE
Single value of type multi-specimen/-object in export

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#447]
## What is the issue ?
The multi-specimen/object record usually come in pairs or larger groups. A single record with the MOS type name is suspicious. 

### Detailed description of the issue. 
During post processing I discovered this 'anomaly' and alerted the project lead. 
Export: NHMD Herba 20231018 16 43 MG.csv
Container name value: MSO2387626551144275769
### Why is it needed/relevant ?
This issues reduces the data quality.
### Explain the need, relevance.
It begs the question: Which other records belong to this group?

### Estimate level of effort required.
 easy

### What could be the challenges ? 
Going back to the collection and finding the specimen
### Remarks
export: 
[NHMD_Herba_20231018_16_43_MG.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13248156/NHMD_Herba_20231018_16_43_MG.csv)

**Comment by JesperMJensen** [comment]
Should be linked to specimen 00936835 in same export: NHMD Herba 20231018 16 43 MG.csv

Image path: N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\JPEGs\WORKHERB0001\2023-10-31\7e7-a-12-10-28-04-0-001-00-000-093dbc-00000.jpeg

![7e7-a-12-10-28-04-0-001-00-000-093dbc-00000](https://github.com/NHMDenmark/Mass-Digitizer/assets/108393212/978d5e17-6836-46a6-9794-c280fa460585)

Seems like a workflow issue, where it wasn't noticed as an MSO until imaging and first barcode (00936835) was already assigned as a single specimen, when second (00937321) was added.

**Comment by RebekkaML** [comment]
fixed in Specify by adding container ID MSO2387626551144275769 to specimen 00936835.
