### ISSUE TITLE
45 records with the same container name, Vascular plants

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#449]
##  What is the issue ?
Potential error in that there are 45 specimens marked with the same container-name.

### Detailed description of the issue. 
The records have this container-name: MSO1680486184909650397
Please see the attachment:  
[NHMD_Herba_20231019_16_26_SS.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13249967/NHMD_Herba_20231019_16_26_SS.csv)

It could be that the container radio button was not reset and the value applied to too many specimens.

## Estimate level of effort required.

Easy
###  How to approach it?
Please check the box 144 to see if in fact there is an issue.

**Comment by RebekkaML** [comment]
Only the first 2 numbers, 937412 and 937413 are an MSO, I checked all the others and they are regular single specimen sheets. This will be updated in Specify in a next step. 
Reference image for the MSO: "N:\SCI-SNM-DigitalCollections\DaSSCo\MASTER_IMAGE_STORE\JPEGs\WORKHERB0001\2023-11-8\7e7-a-14-09-31-19-0-001-00-000-04bfbd-00000.jpeg"

![7e7-a-14-09-31-19-0-001-00-000-04bfbd-00000](https://github.com/NHMDenmark/Mass-Digitizer/assets/144137243/dc8a40d1-7e64-4ca5-b573-0fdfcc730d40)

**Comment by RebekkaML** [comment]
the MSO was corrected in the export file and it was moved to the 1.Exported files from App folder for importing and will then appear correctly in Specify.
