### ISSUE TITLE
Solitary "multiple specimens on one object" value in Digi app export

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#450]
## What is the issue ?
The multi-specimen/object record usually come in pairs or larger groups. A single record with the MSO type name is suspicious. 

### Detailed description of the issue. 
During post processing I discovered this 'anomaly' and alerted the project lead. 
Export: NHMD_Herba_20231031_15_22_JMJ.csv
Container name value: MSO7377688206342114275
### Why is it needed/relevant ?
This issues reduces the data quality in that the container name associates multiple elements through that name.
### Explain the need, relevance.
It begs the question: Which other records belong to this group?

### Estimate level of effort required.
 easy

### What could be the challenges ? 
Going back to the collection and finding the specimen
### Remarks
Export: 
[NHMD_Herba_20231031_15_22_JMJ.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/13267064/NHMD_Herba_20231031_15_22_JMJ.csv)

**Comment by PipBrewer** [comment]
From a quick glance at this, it looks like the isolated container specimens just need recording somewhere for updating in Specify (need to record the container string exactly) and then this can get pushed back to Jan to import.

**Comment by RebekkaML** [comment]
Should be linked to specimen 00940510 in DigiApp export from 26.10.2023: "N:\SCI-SNM-DigitalCollections\DaSSCo\DigiApp\Data\3.Imported specify\NHMD-Herba-20231026-12-00-MG-win-1252.tsv"

It looks like this sheet wasn't recognised as an MSO until imaging, so that a second barcode and the container type were only added later on. This is also added as a comment in the DigiApp: "MSO with NHMD00940510".

**Comment by RebekkaML** [comment]
The corresponding export file has been checked and moved to 1.Exported files from App for importing into specify. Once this is done, the specimens can be connected to the correct MSO there.
@jlegind, can you let me know when this file is in Specify? Thanks!

[NHMD_Herba_20231031_15_22_JMJ_corrected.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/14050468/NHMD_Herba_20231031_15_22_JMJ_corrected.csv)

**Comment by RebekkaML** [comment]
The file has been imported to Specify and I connected the specimens to their containers: 940510 connected with 941055 in MSO7377688206342114275; 940582 connected with 941079 in MSO9126756660449774546. with this, the problem is fixed and everything is correctly associated in specify.
