### ISSUE TITLE
Broad geographic regions in the Digi app are not always matching what Specify expects (ENTOMOLOGY)

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#451]
##  What is the issue ?
Workbench balked at an import containing the Broad geo region name 'Denmark' because it is not available in the Specify entomology pick list. The closest value is 'Dania'.

### Detailed description of the issue. 
When validating the entomology import, workbench refused the broad geographic region value 'Denmark'. 

### Why is it needed/relevant ?
While this is fixable in the workbench process, it is a manual step and if we could save the handful of minutes it takes to correct this, that is a real gain in terms of efficiency. 

### Estimate level of effort required.
Easy

### What is the expected acceptable result.
The digi app and Specify being lined up with regards to Broad Geographic Regions.

**Comment by FedorSteeman** [comment]
Resolved

**Comment by PipBrewer** [comment]
Denmark is what is on the labels and is the correct value for NHMD entomology. The predefined data in Specify should be Denmark. The value in the app needs to be changed back to Denmark.

**Comment by FedorSteeman** [comment]
After discussing this on Slack we converged on the idea that the lists for BGR could be kept as part of the source code. This way, we could better keep track of these lists and only need to make sure they're synced to Specify. Alternatively, we could maintain them in Specify and sync from there.

**Comment by FedorSteeman** [comment]
Fixed in the app and in Specify by changing "Dania" back to "Denmark".
