### ISSUE TITLE
New process for spreadsheet files

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#456]
Ultimately we want to automate the movement and processing of the Digi App export files. Until then, can we do the following:

When exporting from the App, please follow the current naming convention but add "_original" at the end. The exports go initially into N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\0.For checking for Chelsea to check.

If Chelsea needs to modify any of the spreadsheets, she saves them (so there is a copy) and changes "_original" to "_modified". She then moves the modified version or the original version if there have been no modifications to N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\1.Exported files from App to be processed. Originals that have been modified can go straight to: N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\4.Archive

When a spreadsheet from N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\1.Exported files from App is ready to be processed, a copy is saved and the "_original" suffix is changed to "_processed" on the copy. It can be moved to the next folder "N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\2.PostProcessed_openRefine". The original files can now be put in N:\SCI-SNM-DigitalCollections\DaSSCo\Digi App\Data\4.Archive

**Comment by PipBrewer** [comment]
@chelseagraham Can you confirm the above and inform the digitisers/update relevant training documentation?
@jlegind Can you confirm the above and implement this?

**Comment by jlegind** [comment]
testeset
