### ISSUE TITLE
Catalog number repeated in Digi app export

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#459]
##  What is the issue ?
A duplicate catalog number was discovered in one of the downloads: NHMD-PinnedInsects-20231031-16-27-SS-win1252.tsv

### Detailed description of the issue. 
During the effort to investigate the diverging import numbers #458 , a duplicate catalog number showed up.
The offending catalog number is 1650349

### Estimate level of effort required.
Not applicable.
The duplicate record was not imported into Specify due to the way Specify workbench operates, so this is not a problem that needs fixing, so to speak.
I suppose that it might be a scanner read-error at play, though the preceding number is 001650348 and the number following the twin pair is 001650350. If a read error occurred I would assume that the error would have created a gap in the sequence of catalog numbers, like so: 001650348, 001650349, 001650349, 001650351 - or a variation thereof. 

[NHMD-PinnedInsects-20231031-16-27-SS-win1252.txt](https://github.com/NHMDenmark/Mass-Digitizer/files/13513533/NHMD-PinnedInsects-20231031-16-27-SS-win1252.txt)

**Comment by PipBrewer** [comment]
This was a repeat of exactly the same information from one line to the next. It is probably just accidentally beeping the barcode twice. This will regulary happen. This should be caught be workbench. @jlegind How was this handled?

**Comment by FedorSteeman** [comment]
Specify Workbench will prevent the import of a duplicate catalogue number. Depending on how frequently this happens it could be dealt with using a manual check. We could prevent the entry of a duplicate catalogue number during digitization, but this will be limited to each session. 

@bhsi-snm Is the requirement here to prevent duplicate entry during a single digitisation session?

**Comment by bhsi-snm** [comment]
I think it is ok as long it is caught while workbench import or future imports in Specify.
