### ISSUE TITLE
Hybrid species entered in the notes field in the DigiApp

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Mass-Digitizer#470]
##  What is the issue ?
Hybrids (Anthemis arvensis x cotula, Anthemis arvensis x tinctoria) were entered into the notes field instead of the taxon field .
The file is: 
[NHMD_Herba_20231019_16_26_SS_corrected.csv](https://github.com/NHMDenmark/Mass-Digitizer/files/14050249/NHMD_Herba_20231019_16_26_SS_corrected.csv)

But there will be more exports with the same problem. 

# Detailed description of the issue. 
The hybrids should be in the taxonomy, not in the notes field. However, @FedorSteeman informed me, that the GREL script for processing these files in openRefine can't handle Hybrids yet and these need to be fixed after openRefine and before importing them into specify, which makes the workflow much more complex. 

I informed @jlegind of this issue and he ran the file through openRefine and then sent it back to me. I then fixed the Hybrids and sent the file back again. In the long run we need a better  solution for this.

## Why is it needed/relevant ?

Handling Hybrids like this makes it much more complicated and creates a lot of extra work during data processing, especially once we work with the new taxon spine that allows Hybrids in the DigiApp.

**Comment by FedorSteeman** [comment]
I may take this along together with a general revision of the Postprocessing script. I think the fix is relatively easy: It just needs a step to deal with hybrids.

**Comment by FedorSteeman** [comment]
I think there's a misconception here: @RebekkaML  entered a hybrid that is unknown to the taxon spine, so therefore a note was added to the note field and the taxon was marked as a new one. So this behaviour is correct. 

What needs to be changed is the handling of (new) hybrids in the post-processing script.

**Comment by FedorSteeman** [comment]
I noticed that there are already two issues that pertain the handling of hybrids in either the app itself or during post-processing: #346 and #472 

So therefore this ticket can be closed.
