### ISSUE TITLE
Old records associated with containers through the notes field

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#473]
##  What is the issue ?
I noticed that an export contained records referencing other records through the notes field. The notes field reads:
`MSO with NHMD00940510`

## Details
The reference in the first record catalog number `00940510` could not be found in the dataset itself. This means it probably references a record in another dataset export.
The other record has this reference `00940582` which also doesn't exist in the export file.
There is a single record having the MOS signature: `MOS with NHMD00936835`

## Why is it needed/relevant ?
This issue stems from a time when the Digi app did not have a solid feature for dealing with Multi Specimen Objects or Multi Object Specimens. 
We want the container object to be referenced consistently which is why we can't have these band aid measures lingering in Specify.
There are a total of three records in Specify that conform to this pattern: `LIKE 'mso%'` abd they have the following catalog numbers:
000930922, 000931477, 000935037
And another one with the `MOS with NHMD00936835` pattern:
000937321

## What is the expected acceptable result.
Consistent container associations: Records attached to one container must share the same container ID.

##  How to approach it?
I suppose that applying the correct ID to both records through the Specify interface should solve it:
ID: MSO[19 digit random number] like so `MSO8406649029555393284`
I suggest minting a new identifier for each of the four record pairs.

### Is there a potential risk to this. 
There might exist other records suffering the same issue, but having the container association written up differently.

**Comment by FedorSteeman** [comment]
@jlegind Is this to be fixed manually in Specify then and will you do this?

**Comment by AstridBVW** [comment]
> Is this to be fixed manually in Specify then and who will do this? @jlegind @RebekkaML @AstridBVW

@FedorSteeman I am already working on this :)
