### ISSUE TITLE
Taxon SPID not persisted in the local DB specimen table

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#475]
**Describe the bug**
When testing the Digi app the property taxonspid is not applied in the specimen table.

**To Reproduce**
1. Log in to the DaSSCo digi app
2. Fill out the form and save
3. Check the specimen table in DBBrowser viewer
4. See that the taxonspid is always set to 0

**Expected behavior**
The taxonspid is derived from a spid column and should have a number.

**Please complete the following information:**
 - version 1.1.24
 - The taxonspid is set to 0

**Export file**
[specimenTable.xlsx](https://github.com/NHMDenmark/Mass-Digitizer/files/14140295/specimenTable.xlsx)

**Additional context**
The post processing GREL script relies on the taxonspid to identify novel taxon names. A 0 signifies a new taxon and the 'newtaxon' flag will be set.

**Possible solution**
We could rely on the remarks field to look for this pattern: `| Verbatim_taxon: the_novel_name`

**Comment by jlegind** [comment]
Linked in the original post.

**Comment by FedorSteeman** [comment]
The needed changes to the GREL script have been dealt with using fix https://github.com/NHMDenmark/Mass-Digitizer/commit/21a569fb0a34565e7e130293fb7857d617f7ec30

@jlegind Could you please test this again?
