### ISSUE TITLE
App version 1.1.30: Deleting a previous containername does not remove the corresponding containertype 

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#481]
**Describe the bug**
When stepping back through the digitized records and removing a containername will not remove its brother the containertype.

**To Reproduce**
1. In the Digi app enter a handful of records with 'Multiple specimens on one object' radio button set.
2. Step back to an earlier record and delete the 'Containerid' to simulate a situation where the digitizer forgot to reset the radio button.
3. Save the record
4. See the behavior in the DB: The Containerid is removed, yet the Containername remains

**Expected behavior**
The two concepts belong together and I think they should both be removed when the Containerid is deleted.

**Please complete the following information:**
 - version 1.1.30
 - In specify a record might be created with the container name but no identifier to associate it with the other record(s).

**Comment by FedorSteeman** [comment]
Fixed.
