### ISSUE TITLE
Digi app v. 1.1.30 novel taxon name notes are not populated.

### ISSUE THREAD

**Issue by jlegind** [NHMDenmark/Mass-Digitizer#482]
**Describe the bug**
For new names the notes field in the specimen table is not populated.

**To Reproduce**
1. Log in as NHMA or NHMD
2. Create a record with a novel name
***For NHMA:***
1. tab out of the 'Taxon number' field 
2. See the Taxon name being deleted.

**Expected behavior**
When a name not existing in the taxonomy is submitted, it should:
- Be created in the specimen table in the app DB
- Name marked with a note/remark stating that the name is new: `| Verbatim_taxon: [the new name]`

**Please complete the following information:**
 - version 1.1.30
 - specify is not getting data flagging taxonomic names not already in the taxonomic spine.

**Comment by FedorSteeman** [comment]
This is no longer required as per #457
