### ISSUE TITLE
New taxon name that includes author name prevents rank determination.

### ISSUE THREAD

**Issue by FedorSteeman** [NHMDenmark/Mass-Digitizer#484]
If the full name of a novel taxon (i.e. unknown to the taxon spine) is entered including any author names, this would mess up the code trying to guess the taxon rank. Leaving out the author name will make it harder to precisely identify the taxon in question. So there should be some way to include author name without causing problems for rank guessing.

**Comment by FedorSteeman** [comment]
I cannot think any clever solution that would not require special action from the side of the digitizer... This is because the author field is quite unpredictable as far as number of tokens and punctuation. 

There are the following options: 
1. Add an extra input field for the author name alone 
2. Instruct the digitizer to separate author from the rest of the full taxon name with an underscore. 

@bhsi-snm Please evaluate these two suggestions.

**Comment by FedorSteeman** [comment]
Alternatively, we could simply add a dropdownlist from which the digitizer can choose the taxon rank. This is probably the most fail-safe.

**Comment by bhsi-snm** [comment]
I have discussed it with @chelseagraham. She thinks that underscore + taxon rank dropdown is the best solution, same as you but I think for now we can live with the underscore because we can easily incorporate that (only the _before authorname). It is easiest to implement and would be a minor change in the digitiser's workflow.

**Comment by bhsi-snm** [comment]
@FedorSteeman can you please give a couple of examples to explicitly show how this is supposed to be used ?

**Comment by FedorSteeman** [comment]
@bhsi-snm Exactly as @chelseagraham surmised.

**Comment by chelseagraham** [comment]
Just as an update: I have communicated to the digitizers the protocol for when encountering new taxon. They informed me that often the folders do not include the year, only author.
