### ISSUE TITLE
Ensuring correct file names on Digi app exports

### ISSUE THREAD

**Issue by JesperMJensen** [NHMDenmark/Mass-Digitizer#489]
During post processing of digi app exports, a file was discovered with the name 'NHMD_Herba_20231117_15_30_RL_original.csv', but containing pinned insect data.

We want to ensure the correct file naming based on the collection, in this example:
'NHMD_PinnedInsects_20231117_15_30_RL_original.csv'

Suggestions to avoid this error in the future:
- Create subfolders in 0.ForChecking, named "PinnedInsects", "Herbarium" and any future collections.
- Create a "dummy" file, to copy the name from, i.e. "NHMD_PinnedInsects_YYYYMMDD_HH_MM_XYZ_original.csv" and "NHMD_Herba_YYYYMMDD_HH_MM_XYZ_original.csv"
- Make an extra effort to check that the file name is correct, when moving files from 0ForChecking to 1.Exported files from App.

Possible issues:
We must make sure this change in structure folder does not inhibit Bhupjits quest to automate the post processing.

**Comment by PipBrewer** [comment]
@AstridBVW DOes the new folder structure help with the above issue? Is there anything specific we need to communicate with digitisers to help prevent this or any suggestions?

**Comment by AstridBVW** [comment]
@PipBrewer Yes, the new folder structure should solve this issue. I will make sure that all digitisers are informed when the new folder structure is fully implemented and how to use the new structure to ensure correct naming of export files.
