### ISSUE TITLE
Add Store Under name = Yes to GREL script for NHMD Vascular Plants taxonomy

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#490]
Vascular Plants specimens are physical organised by the taxonomy which is listed on the front of the folders they are stored in. This taxonomy may differ to that on the specimen sheet labels, or the specimen may be redetermined and their may be a temporal gap between that redetermination and it being physically moved to another folder with the correct taxonomic name. For these reasons it is useful to indicate in Specify what name the specimen is physically stored under. This is the Stored Under Name. During initial DaSSCo digitisation (before transcription), we are currently ascribing only the name on the folder/drawer (i.e., the stored under name) to the specimen. Hence, we should indicate this by checking the tick box associated with that taxonomic determination during import to Specify. This can be achieved by modifiying the GREL script.

We should also retrospectively add this for all previously imported specimen records for NHMD vascular plants.

![Uploading stored under.png…]()

**Comment by bhsi-snm** [comment]
@AstridBVW @PipBrewer has recommended that this might be a good way for you to get hands-on experience with GREL scripting - update the current GREL script to resolve the above issue.  There are a couple of ways to approach it either we can request @FedorSteeman to introduce our current GREL script and explain it in detail, and then you can come up with a suggestion on how to augment it, or alternatively you can try and go through the script yourself, ask any relevant question and then suggest a solution to @FedorSteeman. I know you are busy this week so, no need to hurry but let us know how you want to proceed.

**Comment by AstridBVW** [comment]
@bhsi-snm I would like to try and go through the script myself and then suggest a solution to @FedorSteeman. I will let you know if I end up needing more details on the GREL script from Fedor.

**Comment by FedorSteeman** [comment]
@AstridBVW  Just in case you might get stuck don't hesitate to reach out to me by mail or phone.

**Comment by AstridBVW** [comment]
This has been added to the GREL script as an additional column with the value "True" for all records.
