### ISSUE TITLE
Rename "new taxon" flag to "check taxon"

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Mass-Digitizer#501]
The "new taxon" flag ( #455 ) in Specify7 should be renamed into "check taxon" flag, since we want to use it for all taxa/authors that are uncertain, not just the newly added ones. 
For example, there might be a taxon that already is in Specify, but with a different author. This would also need to be checked, so the flag should also represent this kind of issue.

**Comment by PipBrewer** [comment]
@FedorSteeman When you have a bit of time, could you have a look at this task?

**Comment by FedorSteeman** [comment]
I can very quickly re-caption this for all collections.

**Comment by FedorSteeman** [comment]
Re-captioned for relevant collections
