### ISSUE TITLE
Need to update GREL script to reflect change in Specify to check taxon flag

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#508]
See  Rename "new taxon" flag to "check taxon" #501 

Update GREL script
Update GREL script documentation

**Comment by AstridBVW** [comment]
During the imports I found out that the mapping is actually not affected by this. Even though the label has been changed for the yesNo-box in Specify, the mapping stayed intact. So there is no need to update the GREL script, it would just be extra unnecessary work. It would be better to focus on updating the documentation for the workbench mapping to show the link between the two. 

@PipBrewer Do you approve?

**Comment by PipBrewer** [comment]
Sounds sensible @AstridBVW

**Comment by AstridBVW** [comment]
OK, I will then close this ticket and make sure to include it in the documentation for workbench.
