### ISSUE TITLE
Find and delete all notes (DaSSCo remarks) in Specify that are associated with closed issues

### ISSUE THREAD

**Issue by AstridBVW** [NHMDenmark/Mass-Digitizer#511]
When we were still sorting out how to deal and document the different issues that could be encountered when digitising, we were using the notes field in the DigiApp a lot to note down a specific issue with a specimen or for adding information about associations with other specimens. The notes would stay in the export file all the way to being imported, and we would create tickets for some of these to make sure it was dealt with in the checking and/or post-processing phase. But now after the issues/tickets have been resolved/closed, the notes are still in Specify. These need to be found and deleted since they are no longer relevant and could cause confusion since it is not clear in Specify that they are connected to issues that have been resolved.

**Comment by AstridBVW** [comment]
I have looked in Specify and there seems to be a bit of cleaning necessary in regard to the remarks field.
Before the DaSSCo remarks table was implemented, everything written in the notes field in the Digi App was mapped to the remarks field on the collection object form. I assume some of these will need to be moved to their proper place in the DaSSCo remarks table with addition of the source and date information. 

These are old notes from before we had proper protocols in place for some of the common issues we encounter while digitising. I will need some guidance on how to deal with some of these. 

I have exported the relevant records and the notes from Specify:
[Ticket 511_CO.remarks.csv](https://github.com/user-attachments/files/16158030/Ticket.511_CO.remarks.csv)

**Comment by AstridBVW** [comment]
This ticket is related to #496

**Comment by AstridBVW** [comment]
Almost all of the records have now been cleaned or investigated and then cleaned.

A lot of them had a "Verbatim_taxon" remark from when we were using an older version of the DigiApp. For the records where the remark matched the determination, the remark was just deleted. Some of the records where they did not match were investigated, corrected and then the remark was deleted.  This has been done for both Botany and Entomology. A few of these are left (Botany), Rebekka will handle those. 

@RebekkaML when you have resolved the remaining records, would you please update the ticket and then close it?

Other kinds of remarks were investigated/checked and the remarks were either deleted or moved to the DaSSCo remarks table where source and date were added. For some the wording was changed to matched the protocols we have established (e.g. specimen obscured, label obscured).

**Comment by RebekkaML** [comment]
I deleted most of the remaining "Verbatim_taxon" remarks today after comparing them to the actual folder labels at Priorparken and finding out what the correct taxon is. 

These cases were the barcode numbers 942948 - 942954, which were in Specify as chrysanthemum parthenium f. flosculosum, but they had the remark "Verbatim_taxon:Chrysanthemum leucanthemum f. flosculosum". The folder labels confirmed that the first version with "parthenium" was the correct one and I deleted the comments.

There is a single remaining case now, specimen 946683, which has the taxon "Filago arvensis" but a note in the comments that says "Verbatim_taxon:filago arvensis x germanica", which the folder label confirmed is the correct taxon. When trying to fix this, there was an error in the Specify taxon tree, it is described in https://github.com/NHMDenmark/DanSpecify/issues/289. Fedor will have a look at this, until then I am putting this issue into Backlog.

**Comment by RebekkaML** [comment]
Issue https://github.com/NHMDenmark/DanSpecify/issues/289 has been resolved and I edited the last remaining entry. It is now correctly assigned to Filago arvensis x germanica and the comment has been deleted. 

With that, this issue is resolved and can be closed.
