### ISSUE TITLE
Can't add author name with Apostrophe in DigiApp

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Mass-Digitizer#513]
When trying to enter a new taxon with an author name with an Apostrophe (e.g. "Sigesbeckia flosculosa l'Herit" into the DigiApp, an error message pops up. We cannot enter the name with the apostrophe. 

Until this is fixed, the working solution is: For now we entered it into the App with a space instead of the apostrophe and put the correct name into the notes field.

![Image](https://github.com/NHMDenmark/Mass-Digitizer/assets/144137243/89ab2c88-ec41-43a1-bca2-ad2641bd4367)

Those names are probably not very common, but we already encountered it once and need to either fix this in the app or have a protocol for how to deal with it.

**Comment by FedorSteeman** [comment]
I fixed this by replacing apostrophes with curly apostrophes (’) both in the digi app and in Specify.
