### ISSUE TITLE
Add DaSSCo remarks table in Specify for NHMA Entomology

### ISSUE THREAD

**Issue by AstridBVW** [NHMDenmark/Mass-Digitizer#520]
A table version of remarks was previously added to the Specify UI for NHMD. A similar remarks table should be implemented for NHMA Entomology.

For NHMD it is the Collection Object Properties table that has been used to implement this. The standard Collection Object Remarks has been retained.

As for NHMD the table should include four fields:

1. Text field labeled "Remark"
2. Text field labeled "Source"
3. Date field labeled "Date"
4. yesNo field labeled "Valid"

The table itself should be named "Collection Object Remarks".

**Comment by FedorSteeman** [comment]
For NHMA Entomology, the schema config has been adjusted to match the CollectionObjectProperty table captions. 

However, I noticed that in NHMD Entomology, the YesNo1 field was not yet marshalled i.e. re-captioned as "Valid". I did this right away, so now it's the same in both ends. For NHMD Vascular Plants all was fine. 

@AstridBVW  Please verify that everything is as it should be, so we can close this ticket.

**Comment by AstridBVW** [comment]
@FedorSteeman Have you only made adjustments to the schema config for NHMA Entomology? Because the CollectionObjectProperty table was not on the UI for NHMA Ento so the UI should also be adjusted. It is not on the UI now, just checked.

**Comment by FedorSteeman** [comment]
Nååå, yes! 

It's added now.

**Comment by FedorSteeman** [comment]
Considered done.
