### ISSUE TITLE
C-V-Gen General Herbarium in Notes field

### ISSUE THREAD

**Issue by beckerah** [NHMDenmark/Mass-Digitizer#546]
Starting today (Nov 6), digitizers in the herbarium will be digitizing some non-Danish specimens. These will need a different storage location noted on them in their Specify records. For now, they'll just add "C-V-Gen General Herbarium" to the notes field, but I'll need to figure out exactly what to do with that information before getting these into Specify.

Related to issue [#543](https://github.com/NHMDenmark/Mass-Digitizer/issues/543)

**Comment by beckerah** [comment]
From Sara, about the exports containing this info:
The additional numbers after "C-V-Gen General Herbarium" is additional storage information Jens provided. I don't know if this level of storage information will be registered for the General Herbarium, but I thought better safe than sorry.
So the first number is cabinet number (1 - 4272, 4975) and the second number is shelf number (1-6).

**Comment by beckerah** [comment]
Specify records for NHMD Herbarium include the following relevant options for Storage info:
-Parent: Priorparken
-Name: C-V-Gen General Herbarium
-Level: Collection (though you can also select from this list: Room, Aisle, Cabinet, Shelf, Box, Rack, Cryo Box, Vial)

Workbench seems to include mapping to the following:
-Preparations > #1 > Storage > Level (Collection, etc) > Name

Question for @FedorSteeman or @Sosannah: 
The Danish herbarium collections in the Specify storage tree include shelf and/or box numbers. Is it a problem if I map to cabinet and shelf numbers for the general herbarium collection without these already existing in the storage tree?

**Comment by beckerah** [comment]
Per Fedor (via Slack): "It should be able to match collection "C-V-Gen General Herbarium" collection in the tree and it will add the child nodes there."

So just need to make sure the collection gets mapped correctly, and can add the shelf and cabinet numbers to the storage tree upon import. (Double-check how this is mapped for the Danish herbarium specimens for NHMD.)

**Comment by beckerah** [comment]
> Let me know how it went. Also: The post-processing script would need to be adapted as to retain the collection column for mapping purposes.

@FedorSteeman It went great except that at some point in my post-processing, the cabinet numbers got turned into integers with decimal points so they look like this: 176.0, 260.0, etc. I didn't catch it before importing to Specify so now they'll need to be cleaned up. Thankfully there are only 10 of them. Frustrating because I noticed this had happened to the shelf and box numbers and fixed those, but I forgot to check the cabinet numbers.

As for updating the post-processing script: the DigiApp exports use the verbiage "C-Danish Herbarium" as part of the storagefullname field. The full string looks like this: Natural History Museum of Denmark | Priorparken | C-Danish Herbarium | Box 791. 
Of course, the way it's written in Specify is "C-V-DK Danish Herbarium" so it will need to be updated to that via the script. (Unless it's easy to update it in the DigiApp db!)

**Comment by FedorSteeman** [comment]
> It went great except that at some point in my post-processing, the cabinet numbers got turned into integers with decimal points so they look like this: 176.0, 260.0, etc. I didn't catch it before importing to Specify so now they'll need to be cleaned up. Thankfully there are only 10 of them. Frustrating because I noticed this had happened to the shelf and box numbers and fixed those, but I forgot to check the cabinet numbers.

Did you open & save the file in M$ Excel by any chance? Frustrating indeed! 

> As for updating the post-processing script: the DigiApp exports use the verbiage "C-Danish Herbarium" as part of the storagefullname field. The full string looks like this: Natural History Museum of Denmark | Priorparken | C-Danish Herbarium | Box 791.

Oh, that's right we need to adapt the app first and then the postproc script...

**Comment by RebekkaML** [comment]
Pip asked me to create a datamatrix for "C-V-Gen General Herbarium" and place it at the workstations so that it can be scanned into the notes field rather than having to write it out every time. I will do this tomorrow when I'm in Priorparken.
