### ISSUE TITLE
Q1 2025: Requests for updates to Mass Digitisation App

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Mass-Digitizer#548]
PLEASE NO MORE ADDITIONS TO THIS TICKET
further additions can be added to the next ticket for Q2 2025: https://github.com/NHMDenmark/Mass-Digitizer/issues/553

Please add requests for updates to the DigiApp to this ticket.

These will be addressed and prioritised on a quarterly basis.

Next review will be in December 2024 / early January 2025 for implementation of agreed updates starting in January 2025.
Discussed at digitizer meeting 10.12.2024.

The following things should be implemented:
- add a specimen counter to the DigiApp: https://github.com/NHMDenmark/Mass-Digitizer/issues/537
- explore possibilities for curser to return to barcode field: https://github.com/NHMDenmark/Mass-Digitizer/issues/526
- delete record button: https://github.com/NHMDenmark/Mass-Digitizer/issues/554

The possibility of exporting the data directly from the app instead of having to open the database was always planned, but it is unclear when and how this can be implemented. Pip and Fedor will discuss this further, I pushed it to the next quarterly ticket for now.

**Comment by Gomismis** [comment]
Make the cursor always return to the barcode field! ex when you select MSO/MOS or when you type in the taxon name the cursor goes to the next field, but it would make things much more effective if it jumped to the barcode field (as scanning the barcode always follow when selecting MSO/MOS).

**Comment by Gomismis** [comment]
Add a counter in the app you you can se how many specimens are scanned to the database.

**Comment by Gomismis** [comment]
A delete record button for when you make mistakes. I could have a pop up saying: ''you are now deleting a record'' --> ok, to avoid mistakes.

**Comment by RebekkaML** [comment]
At the entomology catch up meeting today (05.12.2024), Anders suggested to add a feature to the App that enables us to export (and delete) data directly from the DigiApp instead of the database, so that we wouldn't have to open the database at all. This would make some things easier, but I don't know how feasible this is.
